const countries = {
    'A': ['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan'],
    'B': ['Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi'],
    'C': ['Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo, Democratic Republic of the', 'Congo, Republic of the', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic (Czechia)'],
    'D': ['Denmark', 'Djibouti', 'Dominica', 'Dominican Republic'],
    'E': ['East Timor (Timor-Leste)', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia'],
    'F': ['Fiji', 'Finland', 'France'],
    'G': ['Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana'],
    'H': ['Haiti', 'Honduras', 'Hungary'],
    'I': ['Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Italy'],
    'J': ['Jamaica', 'Japan', 'Jordan'],
    'K': ['Kazakhstan', 'Kenya', 'Kiribati', 'North Korea', 'South Korea', 'Kuwait', 'Kyrgyzstan'],
    'L': ['Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg'],
    'M': ['Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar (Burma)'],
    'N': ['Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia', 'Norway'],
    'O': ['Oman'],
    'P': ['Pakistan', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal'],
    'Q': ['Qatar'],
    'R': ['Romania', 'Russia', 'Rwanda'],
    'S': ['Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa','South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria'],
    'T': ['Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu'],
    'U': ['Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States of America', 'Uruguay', 'Uzbekistan'],
    'V': ['Vanuatu', 'Vatican City', 'Venezuela', 'Vietnam'],
    'Y': ['Yemen'],
    'Z': ['Zambia', 'Zimbabwe']
};

const countryToCode = {
    'Afghanistan': 'AF', 'Albania': 'AL', 'Algeria': 'DZ', 'Andorra': 'AD', 'Angola': 'AO',
    'Antigua and Barbuda': 'AG', 'Argentina': 'AR', 'Armenia': 'AM', 'Australia': 'AU', 'Austria': 'AT',
    'Azerbaijan': 'AZ', 'Bahamas': 'BS', 'Bahrain': 'BH', 'Bangladesh': 'BD', 'Barbados': 'BB',
    'Belarus': 'BY', 'Belgium': 'BE', 'Belize': 'BZ', 'Benin': 'BJ', 'Bhutan': 'BT',
    'Bolivia': 'BO', 'Bosnia and Herzegovina': 'BA', 'Botswana': 'BW', 'Brazil': 'BR', 'Brunei': 'BN',
    'Bulgaria': 'BG', 'Burkina Faso': 'BF', 'Burundi': 'BI', 'Cabo Verde': 'CV', 'Cambodia': 'KH',
    'Cameroon': 'CM', 'Canada': 'CA', 'Central African Republic': 'CF', 'Chad': 'TD', 'Chile': 'CL',
    'China': 'CN', 'Colombia': 'CO', 'Comoros': 'KM', 'Congo, Democratic Republic of the': 'CD', 'Congo, Republic of the': 'CG',
    'Costa Rica': 'CR', 'Croatia': 'HR', 'Cuba': 'CU', 'Cyprus': 'CY', 'Czech Republic (Czechia)': 'CZ',
    'Denmark': 'DK', 'Djibouti': 'DJ', 'Dominica': 'DM', 'Dominican Republic': 'DO',
    'East Timor (Timor-Leste)': 'TL', 'Ecuador': 'EC', 'Egypt': 'EG', 'El Salvador': 'SV', 'Equatorial Guinea': 'GQ',
    'Eritrea': 'ER', 'Estonia': 'EE', 'Eswatini': 'SZ', 'Ethiopia': 'ET', 'Fiji': 'FJ',
    'Finland': 'FI', 'France': 'FR', 'Gabon': 'GA', 'Gambia': 'GM', 'Georgia': 'GE',
    'Germany': 'DE', 'Ghana': 'GH', 'Greece': 'GR', 'Grenada': 'GD', 'Guatemala': 'GT',
    'Guinea': 'GN', 'Guinea-Bissau': 'GW', 'Guyana': 'GY', 'Haiti': 'HT', 'Honduras': 'HN',
    'Hungary': 'HU', 'Iceland': 'IS', 'India': 'IN', 'Indonesia': 'ID', 'Iran': 'IR',
    'Iraq': 'IQ', 'Ireland': 'IE', 'Italy': 'IT', 'Jamaica': 'JM',
    'Japan': 'JP', 'Jordan': 'JO', 'Kazakhstan': 'KZ', 'Kenya': 'KE', 'Kiribati': 'KI',
    'Korea, North (North Korea)': 'KP', 'Korea, South (South Korea)': 'KR', 'Kuwait': 'KW', 'Kyrgyzstan': 'KG',
    'Laos': 'LA', 'Latvia': 'LV', 'Lebanon': 'LB', 'Lesotho': 'LS', 'Liberia': 'LR',
    'Libya': 'LY', 'Liechtenstein': 'LI', 'Lithuania': 'LT', 'Luxembourg': 'LU', 'Madagascar': 'MG',
    'Malawi': 'MW', 'Malaysia': 'MY', 'Maldives': 'MV', 'Mali': 'ML', 'Malta': 'MT',
    'Marshall Islands': 'MH', 'Mauritania': 'MR', 'Mauritius': 'MU', 'Mexico': 'MX', 'Micronesia': 'FM',
    'Moldova': 'MD', 'Monaco': 'MC', 'Mongolia': 'MN', 'Montenegro': 'ME', 'Morocco': 'MA',
    'Mozambique': 'MZ', 'Myanmar (Burma)': 'MM', 'Namibia': 'NA', 'Nauru': 'NR', 'Nepal': 'NP',
    'Netherlands': 'NL', 'New Zealand': 'NZ', 'Nicaragua': 'NI', 'Niger': 'NE', 'Nigeria': 'NG',
    'North Macedonia': 'MK', 'Norway': 'NO', 'Oman': 'OM', 'Pakistan': 'PK', 'Palau': 'PW',
    'Palestine': 'PS', 'Panama': 'PA', 'Papua New Guinea': 'PG', 'Paraguay': 'PY', 'Peru': 'PE',
    'Philippines': 'PH', 'Poland': 'PL', 'Portugal': 'PT', 'Qatar': 'QA', 'Romania': 'RO',
    'Russia': 'RU', 'Rwanda': 'RW', 'Saint Kitts and Nevis': 'KN', 'Saint Lucia': 'LC', 'Saint Vincent and the Grenadines': 'VC',
    'Samoa': 'WS', 'San Marino': 'SM', 'Sao Tome and Principe': 'ST', 'Saudi Arabia': 'SA', 'Senegal': 'SN',
    'Serbia': 'RS', 'Seychelles': 'SC', 'Sierra Leone': 'SL', 'Singapore': 'SG', 'Slovakia': 'SK',
    'Slovenia': 'SI', 'Solomon Islands': 'SB', 'Somalia': 'SO', 'South Africa': 'ZA', 'South Korea': 'KR',
    'South Sudan': 'SS', 'Spain': 'ES', 'Sri Lanka': 'LK', 'Sudan': 'SD', 'Suriname': 'SR',
    'Sweden': 'SE', 'Switzerland': 'CH', 'Syria': 'SY', 'Tajikistan': 'TJ', 'Tanzania': 'TZ',
    'Thailand': 'TH', 'Togo': 'TG', 'Tonga': 'TO', 'Trinidad and Tobago': 'TT', 'Tunisia': 'TN',
    'Turkey': 'TR', 'Turkmenistan': 'TM', 'Tuvalu': 'TV', 'Uganda': 'UG', 'Ukraine': 'UA',
    'United Arab Emirates': 'AE', 'United Kingdom': 'GB', 'United States': 'US', 'Uruguay': 'UY', 'Uzbekistan': 'UZ',
    'Vanuatu': 'VU', 'Vatican City': 'VA', 'Venezuela': 'VE', 'Vietnam': 'VN', 'Yemen': 'YE',
    'Zambia': 'ZM', 'Zimbabwe': 'ZW'
};

const countryFacts = {
    'Afghanistan': 'Afghanistan is home to the ancient city of Bamiyan, where giant Buddha statues were carved into cliffs over 1,500 years ago. Although the statues were destroyed in 2001, the site remains a symbol of Afghanistan\'s rich history.',
    'Albania': 'Albania is known as the "Land of the Eagles." Its national flag features a double-headed eagle, symbolizing the strength and bravery of the Albanian people.',
    'Algeria': 'Algeria is the largest country in Africa by land area. The Sahara Desert, which covers a vast portion of Algeria, is the world\'s largest hot desert.',
    'Andorra': 'Andorra is a tiny country nestled in the Pyrenees mountains between France and Spain. It has no army, and its defense is the responsibility of France and Spain.',
    'Angola': 'Angola has one of the most unique currencies in the world—the kwanza. The name "kwanza" comes from the Kwanza River, which is a significant waterway in the country.',
    'Antigua and Barbuda': 'Antigua and Barbuda is famous for its 365 beaches, one for every day of the year! This makes it a popular destination for tourists seeking sun and sand.',
    'Argentina': 'Argentina is known for being the birthplace of the tango, a passionate and dramatic dance that originated in the capital city of Buenos Aires in the late 19th century.',
    'Armenia': 'Armenia was the first country in the world to adopt Christianity as its state religion, back in 301 AD. The country is home to some of the oldest Christian churches in the world.',
    'Australia': 'Australia is the only country that is also a continent. It\'s famous for its unique wildlife, including kangaroos, koalas, and the platypus, an egg-laying mammal.',
    'Austria': 'Austria is the birthplace of Wolfgang Amadeus Mozart, one of the most famous and influential composers of classical music. His birthplace in Salzburg is a popular tourist attraction.',
    'Azerbaijan': 'Azerbaijan is known as the "Land of Fire" because of its natural burning hillsides. These fires are caused by natural gas seeping through the ground, a phenomenon that has been happening for thousands of years.',
    'Bahamas': 'The Bahamas is home to the worlds third largest barrier reef, the Andros Barrier Reef. The country is also famous for its clear, turquoise waters, making it a top destination for snorkeling and diving.',
    'Bahrain': 'Bahrain is an island nation in the Persian Gulf known for its ancient Dilmun civilization, which dates back over 4,000 years. The country is also famous for the Bahrain Grand Prix, a Formula 1 race that takes place on a desert track.',
    'Bangladesh': 'Bangladesh is home to the Sundarbans, the largest mangrove forest in the world, and a UNESCO World Heritage Site. The forest is also home to the Bengal tiger, one of the most iconic and endangered big cats.',
    'Barbados': 'Barbados is known as the "Land of the Flying Fish." The flying fish is a symbol of the island and is featured on its coins. The fish can leap out of the water and glide for long distances.',
    'Belarus': 'Belarus is sometimes called the "Lungs of Europe" because about 40% of the country is covered by forests. The Belovezhskaya Pushcha National Park, shared with Poland, is home to the European bison, the continent\'s heaviest land animal.',
    'Belgium': 'Belgium is famous for its chocolate, waffles, and comic strips. It is the birthplace of famous comic book characters like Tintin and the Smurfs, and it has more comic strip artists per square kilometer than any other country.',
    'Belize': 'Belize is home to the Great Blue Hole, a giant marine sinkhole that is a popular spot for diving. It\'s one of the most famous diving sites in the world and is part of the Belize Barrier Reef Reserve System, a UNESCO World Heritage Site.',
    'Benin': 'Benin is the birthplace of the ancient Kingdom of Dahomey, which was known for its powerful female warriors, often referred to as the "Dahomey Amazons." These women warriors were among the most feared in Africa during the 17th and 19th centuries.',
    'Bhutan': 'Bhutan is the only country in the world that measures its success by Gross National Happiness (GNH) rather than Gross Domestic Product (GDP). This unique approach focuses on the well being and happiness of its citizens.',
    'Bolivia': 'Bolivia is home to Salar de Uyuni, the largest salt flat in the world. When it rains, the salt flat becomes a giant mirror, reflecting the sky and creating an otherworldly landscape that attracts photographers and tourists from around the globe.',
    'Bosnia and Herzegovina': 'Bosnia and Herzegovina has a unique medieval stećak tombstones, which are monumental tombstones that date back to the 12th century. These tombstones are now recognized as a UNESCO World Heritage Site.',
    'Botswana': 'Botswana is home to the Okavango Delta, one of the largest inland deltas in the world. The delta is a lush wildlife habitat, making it one of the best safari destinations in Africa.',
    'Brazil': 'Brazil is the only country in South America where Portuguese is the official language, due to its history as a Portuguese colony. It\'s also home to the Amazon Rainforest, the largest tropical rainforest in the world.',
    'Brunei': 'Brunei is one of the richest countries in the world due to its extensive oil and natural gas reserves. The Sultan of Brunei, who is one of the world\'s longest reigning monarchs, lives in the Istana Nurul Iman, the largest residential palace in the world.',
    'Bulgaria': 'Bulgaria is home to the oldest gold treasure in the world, discovered in the Varna Necropolis. The treasure dates back to around 4,500 BC, making it over 6,000 years old.',
    'Burkina Faso': 'Burkina Faso is known as the "Land of Upright People." The country is famous for its rich tradition of storytelling, music, and dance, and it hosts the Pan African Film and Television Festival of Ouagadougou (FESPACO), the largest African film festival.',
    'Burundi': 'Burundi is one of the few countries in Africa that claims drumming as part of its cultural heritage. The Royal Drummers of Burundi are world famous and have been performing for over 1,000 years, using drums made from hollowed out tree trunks.',
    'Cabo Verde': 'Cabo Verde, also known as Cape Verde, is an island nation in the Atlantic Ocean. It\'s famous for its unique music genre called morna, a soulful and melancholic style that reflects the countrys mix of African, Portuguese, and Brazilian influences.',
    'Cambodia': 'Cambodia is home to Angkor Wat, the largest religious monument in the world. Originally built as a Hindu temple in the early 12th century, it later became a Buddhist temple and is now a symbol of Cambodia\'s rich cultural heritage.',
    'Cameroon': 'Cameroon is known as "Africa in miniature" because it has a variety of landscapes and climates, ranging from tropical rainforests to savannas to mountains. It\'s also home to Mount Cameroon, one of Africa\'s largest volcanoes.',
    'Canada': 'Canada has the longest coastline of any country in the world, stretching over 202,080 kilometers. It\'s also famous for its vast wilderness, with more than half of the country covered in forests.',
    'Central African Republic': 'The Central African Republic is home to the Dzanga Sangha National Park, where you can find the Western lowland gorilla, a critically endangered species. The park is part of a UNESCO World Heritage Site known for its biodiversity.',
    'Chad': 'Chad is home to Lake Chad, once one of the largest lakes in Africa. Although it has shrunk significantly in recent decades, it remains an important water source for millions of people in the region.',
    'Chile': 'Chile is one of the longest countries in the world, stretching over 4,300 kilometers from north to south. It\'s also home to the Atacama Desert, the driest desert in the world, where some areas have never recorded rainfall.',
    'China': 'China is home to the Great Wall of China, one of the Seven Wonders of the Medieval World. The wall stretches over 13,000 miles and was originally built to protect Chinese states from invasions.',
    'Colombia': 'Colombia is the second most biodiverse country in the world, after Brazil. It\'s famous for its coffee, emeralds, and vibrant cultural festivals, like the Barranquilla Carnival, one of the biggest in the world.',
    'Comoros': 'Comoros is one of the world\'s largest producers of ylang ylang, a flower used to make perfume, including the famous Chanel No. 5. The country\'s volcanic islands are also home to a rich marine ecosystem.',
    'Congo, Democratic Republic of the': 'The Democratic Republic of the Congo is home to the Congo River, the second longest river in Africa and the deepest river in the world. The country also contains a large portion of the Congo Basin, which is one of the most important wilderness areas left on Earth.',
    'Congo, Republic of the': 'The Republic of the Congo is known for its vast rainforests and diverse wildlife. The country is part of the Congo Basin, which is often referred to as the "second lung of the Earth" due to its role in absorbing carbon dioxide.',
    'Costa Rica': 'Costa Rica is a leader in environmental sustainability and has one of the highest levels of biodiversity in the world. Despite its small size, it contains 5% of the world\'s species and is known for its extensive network of national parks and protected areas.',
    'Croatia': 'Croatia\'s coastline along the Adriatic Sea is dotted with more than 1,200 islands, making it a popular destination for tourists. The country is also home to the ancient walled city of Dubrovnik, which served as a filming location for the popular TV series "Game of Thrones."',
    'Cuba': 'Cuba is famous for its vintage American cars from the 1950s, which are still in use today due to the trade embargoes that prevented the import of new vehicles. The country is also known for its vibrant music and dance traditions, including salsa and son.',
    'Cyprus': 'Cyprus is the legendary birthplace of Aphrodite, the ancient Greek goddess of love and beauty. The island nation has a rich history with influences from various civilizations, including the Greeks, Romans, and Ottomans.',
    'Czech Republic (Czechia)': 'The Czech Republic is home to the largest ancient castle in the world, Prague Castle, which dates back to the 9th century. The country is also famous for its beer, with Czechs consuming more beer per capita than any other nation.',
    'Denmark': 'Denmark is known as the birthplace of LEGO. The world famous building blocks were invented in 1932 by Danish carpenter Ole Kirk Christiansen. Denmark is also home to the original LEGOLAND theme park, located in Billund.',
    'Djibouti': 'Djibouti is home to Lake Assal, the lowest point in Africa and one of the saltiest bodies of water in the world. The lake\'s salt content is ten times higher than that of the ocean, making it an extreme and unique environment.',
    'Dominica': 'Dominica is often called the "Nature Island of the Caribbean" because of its lush landscapes and numerous natural attractions, including hot springs, waterfalls, and the second largest boiling lake in the world.',
    'Dominican Republic': 'The Dominican Republic shares the island of Hispaniola with Haiti and is famous for being the site of the first permanent European settlement in the Americas, founded by Christopher Columbus in 1492. The capital, Santo Domingo, is home to the oldest cathedral in the Americas.',
    'East Timor (Timor Leste)': 'East Timor, or Timor Leste, is one of the youngest countries in the world, having gained independence from Indonesia in 2002. The country is known for its stunning coral reefs and is a popular destination for divers.',
    'Ecuador': 'Ecuador is one of the only countries in the world named after a geographical feature—the equator, which runs through the country. Ecuador is also home to the Galápagos Islands, where Charles Darwin developed his theory of evolution.',
    'Egypt': 'Egypt is home to the Great Pyramid of Giza, one of the Seven Wonders of the Ancient World. The country is also famous for its rich history of pharaohs, pyramids, and the Nile River, the longest river in the world.',
    'El Salvador': 'El Salvador is known as the "Land of Volcanoes" because it has more than 20 volcanoes, with two being active. The country also has a strong surf culture, with some of the best surfing spots in Central America.',
    'Equatorial Guinea': 'Equatorial Guinea is the only country in Africa where Spanish is an official language. The country\'s capital, Malabo, is located on the island of Bioko, making it one of the few national capitals not located on the mainland.',
    'Eritrea': 'Eritrea\'s capital, Asmara, is known for its well preserved modernist architecture from the 1930s and 1940s, earning it the nickname "Africa\'s Little Rome." The city\'s unique architectural heritage led to its designation as a UNESCO World Heritage Site.',
    'Estonia': 'Estonia is one of the most digitally advanced countries in the world. It was the first country to allow online voting in national elections, and nearly all government services are available online.',
    'Eswatini': 'Formerly known as Swaziland, Eswatini is one of the last remaining absolute monarchies in the world. The country is known for its vibrant cultural festivals, such as the annual Umhlanga, or Reed Dance, where thousands of women participate in traditional ceremonies.',
    'Ethiopia': 'Ethiopia is one of the oldest countries in the world and is often considered the birthplace of coffee. Legend has it that coffee was discovered by an Ethiopian goat herder named Kaldi in the 9th century.',
    'Fiji': 'Fiji is an archipelago of over 300 islands in the South Pacific. It\'s famous for its crystal clear waters, coral reefs, and as the filming location for the movie "Cast Away" starring Tom Hanks.',
    'Finland': 'Finland is known as the "Land of a Thousand Lakes," but it actually has over 188,000 lakes. The country is also famous for its education system, which is considered one of the best in the world.',
    'France': 'France is the most visited country in the world, attracting over 80 million tourists annually. It\'s known for its rich cultural heritage, iconic landmarks like the Eiffel Tower, and its influence on art, fashion, and cuisine.',
    'Gabon': 'Gabon is home to 13 national parks, covering around 11% of the country\'s land area. The Loango National Park is famous for its "surfing hippos" that are often seen playing in the ocean waves along the coast.',
    'Gambia': 'The Gambia is the smallest country on mainland Africa and is almost entirely surrounded by Senegal, except for its small Atlantic coastline. The country is named after the Gambia River, which runs through its entire length.',
    'Georgia': 'Georgia is one of the oldest wine producing regions in the world, with a winemaking tradition that dates back over 8,000 years. The country is also known for its beautiful and diverse landscapes, from the Black Sea coast to the Caucasus Mountains.',
    'Germany': 'Germany is home to the world\'s largest Volksfest, Oktoberfest, held annually in Munich. The festival is famous for its beer, traditional Bavarian costumes, and lively atmosphere, attracting millions of visitors from around the world.',
    'Ghana': 'Ghana was the first African country to gain independence from colonial rule in 1957. The country is also known for its rich cultural heritage, including vibrant festivals, traditional kente cloth, and historical sites like the Cape Coast Castle.',
    'Greece': 'Greece is known as the cradle of Western civilization and the birthplace of democracy. It\'s home to many ancient landmarks, including the Parthenon in Athens and the ruins of Olympia, where the Olympic Games originated.',
    'Grenada': 'Grenada is known as the "Island of Spice" because it\'s one of the world\'s largest producers of nutmeg and mace. The island is also famous for its beautiful beaches and lush rainforests.',
    'Guatemala': 'Guatemala is home to the ancient Maya city of Tikal, one of the most significant archaeological sites in Central America. The country is also known for its vibrant indigenous culture and colorful textiles.',
    'Guinea': 'Guinea is one of the wettest countries in West Africa and is home to the Fouta Djallon highlands, often referred to as the "water tower of West Africa" because many rivers, including the Niger River, have their sources there.',
    'Guinea Bissau': 'Guinea Bissau is known for its archipelago of 88 islands, the Bijagós Islands, which are a UNESCO Biosphere Reserve. The islands are home to unique wildlife, including rare saltwater hippos.',
    'Guyana': 'Guyana is the only English speaking country in South America. It\'s also home to Kaieteur Falls, one of the world\'s most powerful waterfalls, located in the heart of the country\'s pristine rainforest.',
    'Haiti': 'Haiti was the first independent nation in Latin America and the Caribbean, as well as the first post colonial independent black led nation in the world, after winning its independence from France in 1804.',
    'Honduras': 'Honduras is home to the ancient Maya city of Copán, a UNESCO World Heritage Site. The city is famous for its well preserved hieroglyphic stairway, which tells the history of the Maya rulers in intricate detail.',
    'Hungary': 'Hungary is famous for its thermal baths, with more than 1,000 hot springs across the country. Budapest, the capital, is often called the "Spa Capital of the World" due to its numerous historic bathhouses.',
    'Iceland': 'Iceland is known as the "Land of Fire and Ice" because it has both glaciers and volcanoes. It\'s also one of the best places in the world to see the Northern Lights, a natural light display in the sky caused by the solar wind.',
    'India': 'India is home to the Taj Mahal, one of the Seven Wonders of the World. This stunning white marble mausoleum was built by Emperor Shah Jahan in memory of his wife Mumtaz Mahal and is a symbol of India\'s rich history and culture.',
    'Indonesia': 'Indonesia is the world\'s largest archipelago, consisting of over 17,000 islands. It\'s also home to the Komodo dragon, the world\'s largest lizard, found only on a few islands in the country.',
    'Iran': 'Iran, historically known as Persia, is home to one of the world\'s oldest civilizations, with historical and cultural sites dating back to 4,000 BC. The ancient ruins of Persepolis, once the capital of the Persian Empire, are a UNESCO World Heritage Site.',
    'Iraq': 'Iraq is home to the ancient city of Babylon, one of the most famous cities of antiquity. The Hanging Gardens of Babylon, one of the Seven Wonders of the Ancient World, were said to have been located here, although their existence is still debated.',
    'Ireland': 'Ireland is famous for its lush green landscapes, earning it the nickname "The Emerald Isle." It\'s also known for its rich literary history, being the birthplace of renowned writers like James Joyce, W.B. Yeats, and Oscar Wilde.',
    'Italy': 'Italy is home to the city of Rome, known as the "Eternal City." Rome has been a center of history, culture, and religion for over 2,000 years and is home to landmarks like the Colosseum, the Vatican, and the Sistine Chapel.',
    'Jamaica': 'Jamaica is the birthplace of reggae music, a genre made famous by legendary musician Bob Marley. The island is also known for its beautiful beaches, vibrant culture, and as the home of Usain Bolt, the fastest man in the world.',
    'Japan': 'Japan is home to the iconic Mount Fuji, an active volcano and the country\'s highest peak. Mount Fuji is considered a sacred symbol in Japan and has been a source of inspiration for artists and poets for centuries.',
    'Jordan': 'Jordan is home to Petra, an ancient city carved into rose red cliffs, often referred to as the "Lost City." Petra is one of the New Seven Wonders of the World and a UNESCO World Heritage Site, attracting visitors from all over the globe.',
    'Kazakhstan': 'Kazakhstan is the largest landlocked country in the world. The country is also known for the Baikonur Cosmodrome, the world\'s first and largest operational space launch facility, from where the first human, Yuri Gagarin, was sent into space.',
    'Kenya': 'Kenya is famous for its stunning landscapes and incredible wildlife. The country is home to the Great Rift Valley and several national parks, including the Maasai Mara, known for the annual Great Migration of over a million wildebeest and zebras.',
    'Kiribati': 'Kiribati is one of the few countries that are situated in all four hemispheres—Northern, Southern, Eastern, and Western. The country\'s 33 atolls and islands are spread across a vast area in the central Pacific Ocean.',
    'Korea, North (North Korea)': 'North Korea is known for its large scale propaganda and mass games, such as the Arirang Festival, which features synchronized gymnastics and performances involving tens of thousands of participants.',
    'Korea, South (South Korea)': 'South Korea is a global leader in technology and pop culture. It\'s the birthplace of K pop, a popular music genre that has gained worldwide fame, and it\'s also known for its cutting edge technology and innovation, especially in the electronics and automobile industries.',
    'Kuwait': 'Kuwait has one of the highest valued currencies in the world, the Kuwaiti dinar. The country is also known for its oil reserves, which contribute significantly to its wealth and economy.',
    'Kyrgyzstan': 'Kyrgyzstan is known for its breathtaking natural landscapes, especially its mountain ranges, which cover 90% of the country. The country is also famous for its nomadic culture and traditional sports like kok boru, a type of horseback game similar to polo.',
    'Laos': 'Laos is home to the ancient city of Luang Prabang, a UNESCO World Heritage Site known for its well preserved blend of traditional Lao and colonial French architecture. The city is also famous for its hundreds of Buddhist temples.',
    'Latvia': 'Latvia is known for its beautiful and dense forests, which cover about half of the country. It\'s also home to the unique tradition of singing festivals; the Latvian Song and Dance Festival, held every five years, is one of the largest amateur choral events in the world.',
    'Lebanon': 'Lebanon is home to the ancient city of Byblos, one of the oldest continuously inhabited cities in the world. Byblos is also believed to be the birthplace of the modern alphabet, developed by the Phoenicians around 1200 BC.',
    'Lesotho': 'Lesotho is the only country in the world that is entirely above 1,000 meters in elevation, giving it the nickname "The Kingdom in the Sky." The country\'s mountainous terrain is ideal for activities like skiing and hiking.',
    'Liberia': 'Liberia is Africa\'s oldest republic, having declared its independence in 1847. It was founded by freed American slaves, and its capital, Monrovia, is named after James Monroe, the fifth President of the United States.',
    'Libya': 'Libya is home to the ancient city of Leptis Magna, one of the best preserved Roman cities in the Mediterranean. This archaeological site, located near the coast, was once a prominent city of the Roman Empire.',
    'Liechtenstein': 'Liechtenstein is one of the smallest and richest countries in the world. Despite its size, it\'s known for its strong financial sector and beautiful Alpine landscapes, which attract hikers and winter sports enthusiasts.',
    'Lithuania': 'Lithuania was the last country in Europe to convert to Christianity in 1387. The country is also known for its unique Hill of Crosses, a site of pilgrimage that features tens of thousands of crosses placed there by visitors over the years.',
    'Luxembourg': 'Luxembourg is one of the world\'s smallest countries, but it has one of the highest GDPs per capita. It\'s known for its medieval castles, including the impressive Vianden Castle, and for being a founding member of the European Union.',
    'Madagascar': 'Madagascar is the fourth largest island in the world and is home to unique wildlife, with about 90% of its plant and animal species found nowhere else on Earth. The island is famous for its lemurs, colorful chameleons, and the baobab tree.',
    'Malawi': 'Malawi is known as the "Warm Heart of Africa" because of the friendliness of its people. The country is also home to Lake Malawi, one of the largest and deepest lakes in Africa, known for its crystal clear waters and diverse fish species.',
    'Malaysia': 'Malaysia is home to the Petronas Towers in Kuala Lumpur, which were the tallest buildings in the world from 1998 to 2004. The towers remain an iconic symbol of Malaysia\'s modern development and are a major tourist attraction.',
    'Maldives': 'The Maldives is the lowest country in the world, with an average ground level of just 1.5 meters above sea level. The country is famous for its stunning overwater bungalows, crystal clear waters, and vibrant coral reefs, making it a top destination for honeymooners and divers.',
    'Mali': 'Mali is home to the ancient city of Timbuktu, which was once a major center of Islamic learning and trade in Africa. Timbuktu\'s historic manuscripts and mosques are a testament to its rich cultural and academic history.',
    'Malta': 'Malta is known for its rich history, which dates back thousands of years. The country is home to some of the oldest free standing structures in the world, such as the Megalithic Temples, which are older than the pyramids of Egypt.',
    'Marshall Islands': 'The Marshall Islands is a country of atolls and islands spread across the Pacific Ocean. Bikini Atoll, one of its islands, was the site of nuclear testing by the United States in the 1940s and 1950s, and today it is a UNESCO World Heritage Site.',
    'Mauritania': 'Mauritania is known for the ancient city of Chinguetti, which was once an important center for Islamic scholarship. The city\'s ancient libraries contain thousands of medieval manuscripts and are considered a cultural treasure.',
    'Mauritius': 'Mauritius is famous for being the only known home of the dodo, a flightless bird that became extinct in the late 17th century. The bird has since become a symbol of extinction and conservation efforts.',
    'Mexico': 'Mexico is home to the ancient Maya city of Chichen Itza, one of the New Seven Wonders of the World. The pyramid of El Castillo at Chichen Itza is a famous example of Mayan architecture and astronomical knowledge.',
    'Micronesia': 'Micronesia is an island nation in the Pacific Ocean, known for the ancient city of Nan Madol. This city, built on a series of artificial islets, is often called the "Venice of the Pacific" and is a UNESCO World Heritage Site.',
    'Moldova': 'Moldova is one of Europe\'s lesser known wine producing countries, with a winemaking tradition that dates back thousands of years. The country is home to some of the largest wine cellars in the world, including Milestii Mici, which holds the Guinness World Record for the largest wine collection.',
    'Monaco': 'Monaco is the second smallest country in the world, known for its luxury and wealth. The country is famous for the Monaco Grand Prix, a prestigious Formula 1 race that takes place on the streets of Monte Carlo.',
    'Mongolia': 'Mongolia is known as the "Land of the Eternal Blue Sky" because it has more than 250 sunny days a year. The country is also famous for its vast steppes and nomadic culture, with traditional herding practices still common today.',
    'Montenegro': 'Montenegro is known for its stunning natural landscapes, including the Bay of Kotor, often considered one of the most beautiful bays in the world. The country\'s name means "Black Mountain," and it\'s famous for its rugged mountains and picturesque coastal towns.',
    'Morocco': 'Morocco is home to the city of Marrakech, known as the "Red City" because of its red sandstone buildings. The city\'s famous Jemaa el Fnaa square is a UNESCO World Heritage Site, known for its bustling markets, street performers, and traditional Moroccan cuisine.',
    'Mozambique': 'Mozambique has one of the longest coastlines in Africa, stretching along the Indian Ocean. The country is famous for its beautiful beaches, coral reefs, and marine life, making it a popular destination for scuba diving and snorkeling.',
    'Myanmar (Burma)': 'Myanmar is home to the ancient city of Bagan, which has over 2,000 Buddhist temples and pagodas. The city is known for its stunning sunrise views, with hot air balloons offering panoramic vistas of the temple dotted landscape.',
    'Namibia': 'Namibia is home to the Namib Desert, one of the oldest deserts in the world, estimated to be around 55 million years old. The desert is famous for its towering red sand dunes, some of the highest in the world, which create a stunning and unique landscape.',
    'Nauru': 'Nauru is the third smallest country in the world by land area, and the smallest island country. Interestingly, it has no official capital city, with government offices spread across the island.',
    'Nepal': 'Nepal is home to Mount Everest, the highest point on Earth, standing at 8,848 meters (29,029 feet) above sea level. The mountain, known as "Sagarmatha" in Nepali, is a major destination for mountaineers from around the world.',
    'Netherlands': 'The Netherlands is famous for its extensive system of canals, windmills, and tulip fields. The country is also known for its low elevation; about a third of the Netherlands is below sea level, protected by an elaborate system of dikes and levees.',
    'New Zealand': 'New Zealand was the first country in the world to grant women the right to vote, in 1893. The country is also known for its stunning landscapes, which were featured in the "Lord of the Rings" and "The Hobbit" movie trilogies.',
    'Nicaragua': 'Nicaragua is known as the "Land of Lakes and Volcanoes" because of its large number of both. Lake Nicaragua is the largest lake in Central America, and the country has 19 active volcanoes, some of which are popular for hiking and sightseeing.',
    'Niger': 'Niger is home to one of the world\'s largest desert regions, the Sahara, which covers much of the country. The country is also known for the ancient city of Agadez, a UNESCO World Heritage Site with historic mud brick architecture.',
    'Nigeria': 'Nigeria is the most populous country in Africa and is known for its vibrant cultural heritage. It is home to Nollywood, the second largest film industry in the world by volume, producing hundreds of movies every year.',
    'North Macedonia': 'North Macedonia is home to Lake Ohrid, one of the oldest and deepest lakes in Europe. The lake and its surroundings are a UNESCO World Heritage Site, known for their natural beauty and historical significance.',
    'Norway': 'Norway is famous for its fjords—deep, glacially carved valleys filled with seawater. The country is also known for being one of the best places to see the Northern Lights, especially in the northern regions above the Arctic Circle.',
    'Oman': 'Oman is home to the worlds oldest independent Arab state, with a history of continuous leadership dating back more than 2,000 years. The country is also famous for the Frankincense trees in the Dhofar region, which have been harvested for their aromatic resin since ancient times.',
    'Pakistan': 'Pakistan is home to the second highest mountain in the world, K2, also known as Mount Godwin Austen. K2 is part of the Karakoram Range and is considered one of the most challenging peaks to climb due to its steep and icy slopes.',
    'Palau': 'Palau is famous for its pristine marine environments, especially the Rock Islands, a UNESCO World Heritage Site. The islands are known for their unique mushroom like shapes and are surrounded by coral reefs teeming with marine life, making them a paradise for divers.',
    'Palestine': 'Palestine is home to the city of Jerusalem, a city with profound religious significance to Jews, Christians, and Muslims. The Old City of Jerusalem is a UNESCO World Heritage Site and contains important religious sites like the Western Wall, the Church of the Holy Sepulchre, and the Al Aqsa Mosque.',
    'Panama': 'Panama is known for the Panama Canal, one of the most significant engineering marvels in the world. The canal, which connects the Atlantic and Pacific Oceans, revolutionized global trade when it was completed in 1914 and remains a critical shipping route today.',
    'Papua New Guinea': 'Papua New Guinea is one of the most culturally diverse countries in the world, with over 800 different languages spoken. The country is also home to some of the worlds most remote and unexplored rainforests, which are rich in biodiversity.',
    'Paraguay': 'Paraguay is home to the Itaipu Dam, one of the largest hydroelectric dams in the world. The dam, which is located on the Paraná River and shared with Brazil, produces a significant portion of the electricity used in both countries.',
    'Peru': 'Peru is famous for Machu Picchu, the ancient Inca city located high in the Andes Mountains. This UNESCO World Heritage Site is one of the most iconic archaeological sites in the world and attracts visitors from all over the globe.',
    'Philippines': 'The Philippines is made up of over 7,000 islands and is known for its incredible biodiversity, both on land and in the surrounding seas. The Tubbataha Reefs Natural Park, a UNESCO World Heritage Site, is one of the world\'s best diving spots.',
    'Poland': 'Poland is home to the largest castle in the world by land area, Malbork Castle. Built in the 13th century by the Teutonic Knights, this medieval fortress is a UNESCO World Heritage Site and one of Polands most popular tourist attractions.',
    'Portugal': 'Portugal is known for its explorers, including Vasco da Gama, who was the first person to sail directly from Europe to India. The country is also famous for its beautiful coastline and the historic city of Lisbon, one of the oldest cities in Western Europe.',
    'Qatar': 'Qatar is one of the richest countries in the world due to its vast natural gas and oil reserves. The country is also known for its futuristic architecture, particularly in its capital, Doha, where the skyline is filled with strikingly modern buildings.',
    'Romania': 'Romania is home to the region of Transylvania, famous for its medieval castles, including Bran Castle, often referred to as "Dracula\'s Castle." This association with the Dracula legend, created by Bram Stoker\'s novel, has made Transylvania a popular tourist destination.',
    'Russia': 'Russia is the largest country in the world by land area, stretching across 11 time zones. It\'s also home to Lake Baikal, the deepest and oldest freshwater lake in the world, containing about 20% of the world\'s unfrozen freshwater.',
    'Rwanda': 'Rwanda is known as the "Land of a Thousand Hills" due to its mountainous terrain. The country is famous for its mountain gorillas, which can be seen in the Volcanoes National Park, making Rwanda a top destination for wildlife enthusiasts.',
    'Saint Kitts and Nevis': 'Saint Kitts and Nevis is the smallest country in the Western Hemisphere, both in terms of land area and population. The country is known for its beautiful beaches and as a popular destination for eco tourism.',
    'Saint Lucia': 'Saint Lucia is famous for the Pitons, two volcanic spires that are a UNESCO World Heritage Site and one of the most recognizable landmarks in the Caribbean. The island is also known for its lush rainforests and vibrant Creole culture.',
    'Saint Vincent and the Grenadines': 'Saint Vincent and the Grenadines is known for its stunning islands and as a top destination for sailing and yachting. The Tobago Cays, a group of five small islands, are renowned for their crystal clear waters and coral reefs.',
    'Samoa': 'Samoa is known for its traditional way of life called "faa Samoa," which emphasizes community, respect for elders, and cultural traditions. The country is also famous for its natural beauty, including waterfalls, lava fields, and the To Sua Ocean Trench, a unique swimming spot.',
    'San Marino': 'San Marino claims to be the oldest surviving republic in the world, having been founded in 301 AD. The country is entirely surrounded by Italy and is known for its medieval architecture and stunning views from Mount Titano.',
    'Sao Tome and Principe': 'Sao Tome and Principe is one of the smallest countries in Africa, consisting of two main islands in the Gulf of Guinea. The country is known for its rich biodiversity, including many species of birds, plants, and marine life found nowhere else on Earth.',
    'Saudi Arabia': 'Saudi Arabia is home to the two holiest cities in Islam, Mecca and Medina. Every year, millions of Muslims from around the world visit Mecca to perform the Hajj pilgrimage, one of the five pillars of Islam.',
    'Senegal': 'Senegal is known for its vibrant music and dance culture, particularly the genre of mbalax, which blends traditional Wolof music with jazz, soul, and Latin influences. The country is also home to the stunning pink colored Lake Retba, also known as Lac Rose.',
    'Serbia': 'Serbia is home to the world\'s largest Orthodox Christian church, the Church of Saint Sava in Belgrade. The country is also known for its medieval monasteries, vibrant festivals, and as the birthplace of famous inventor Nikola Tesla.',
    'Seychelles': 'Seychelles is an archipelago of 115 islands in the Indian Ocean, known for its pristine beaches, crystal clear waters, and unique granite rock formations. The islands are also home to the Aldabra giant tortoise, one of the largest tortoises in the world.',
    'Sierra Leone': 'Sierra Leone is famous for its diamond mines, which have produced some of the world\'s largest and most valuable diamonds. The country\'s name means "Lion Mountains," a reference to the rugged terrain surrounding its capital, Freetown.',
    'Singapore': 'Singapore is one of the worlds most densely populated countries, yet its also known as one of the greenest cities. The city state is famous for its futuristic architecture, including the Marina Bay Sands and Gardens by the Bay, with its iconic Supertree Grove.',
    'Slovakia': 'Slovakia is home to more than 6,000 caves, many of which are open to the public. The Ochtinská Aragonite Cave, a UNESCO World Heritage Site, is particularly famous for its rare and beautiful aragonite formations.',
    'Slovenia': 'Slovenia is known for its picturesque Lake Bled, which features a small island with a church in the middle and a medieval castle perched on a cliff overlooking the lake. The country is also known for its extensive karst caves, including the famous Postojna Cave.',
    'Solomon Islands': 'The Solomon Islands played a significant role in World War II, particularly in the Battle of Guadalcanal, which was a major turning point in the Pacific theater. The islands are also known for their rich marine biodiversity and traditional Melanesian culture.',
    'Somalia': 'Somalia has the longest coastline on mainland Africa, stretching over 3,300 kilometers along the Indian Ocean. The country is known for its rich history of trade, particularly in the ancient city of Mogadishu, once a major hub for commerce in the region.',
    'South Africa': 'South Africa is known as the "Rainbow Nation" because of its multicultural diversity. The country is also home to Table Mountain, one of the New Seven Wonders of Nature, and is famous for its wildlife, particularly in Kruger National Park.',
    'South Korea': 'South Korea is a global leader in technology and pop culture, especially through K pop and K dramas, which have gained international popularity. The country is also known for its historical sites like Gyeongbokgung Palace in Seoul and the Demilitarized Zone (DMZ) that separates it from North Korea.',
    'South Sudan': 'South Sudan is the worlds newest country, having gained independence from Sudan in 2011. The country is home to the Sudd, one of the world\'s largest wetlands, which plays a crucial role in the Nile River ecosystem.',
    'Spain': 'Spain is famous for its rich cultural heritage, including flamenco music and dance, bullfighting, and its numerous UNESCO World Heritage Sites like the Alhambra in Granada and Sagrada Familia in Barcelona.',
    'Sri Lanka': 'Sri Lanka is known as the "Pearl of the Indian Ocean" due to its stunning natural beauty, including lush rainforests, beautiful beaches, and ancient temples. The country is also famous for its tea, with the highlands producing some of the world\'s best Ceylon tea.',
    'Sudan': 'Sudan is home to more pyramids than Egypt, with the ancient Kingdom of Kush building over 200 pyramids in Meroë, which are now recognized as a UNESCO World Heritage Site.',
    'Suriname': 'Suriname is the smallest country in South America, both in terms of land area and population. The country is known for its diverse cultural heritage, with influences from African, Asian, and European traditions.',
    'Sweden': 'Sweden is known for its high quality of life, extensive welfare system, and as the home of the Nobel Prize. The country is also famous for its beautiful natural landscapes, including the Northern Lights, which can be seen in the northern regions.',
    'Switzerland': 'Switzerland is known for its neutrality, beautiful Alps, and as the headquarters for many international organizations, including the Red Cross and various UN agencies. The country is also famous for its precision watches, chocolate, and banking sector.',
    'Syria': 'Syria is one of the oldest inhabited regions in the world, with its capital, Damascus, considered one of the oldest continuously inhabited cities. Syria was historically a crossroads of civilizations, contributing significantly to human culture and history.',
    'Taiwan': 'Taiwan is known for its technological advancements, particularly in electronics. It is home to some of the worlds leading technology companies, including those that produce the majority of the worlds advanced semiconductors.',
    'Tajikistan': 'Tajikistan is home to the Pamir Mountains, often referred to as the "Roof of the World." These mountains are some of the highest in the world, with stunning landscapes and deep valleys that have been traveled by explorers for centuries.',
    'Tanzania': 'Tanzania is home to Mount Kilimanjaro, the highest peak in Africa, standing at 5,895 meters (19,341 feet). The country is also famous for the Serengeti National Park, where the Great Migration of wildebeest and other animals occurs annually.',
    'Thailand': 'Thailand is known as the "Land of Smiles" because of the friendliness of its people. The country is famous for its beautiful temples, vibrant street markets, and as the only Southeast Asian nation never to have been colonized by a European power.',
    'Togo': 'Togo is one of the smallest countries in Africa, but its known for its cultural diversity. The country has more than 40 ethnic groups, each with its own languages, customs, and traditions. Togo is also known for its beautiful coastline and lush forests.',
    'Tonga': 'Tonga is the only monarchy in the Pacific Islands and one of the few remaining monarchies in the world. It\'s known for its traditional Polynesian culture, and it was never colonized by a foreign power.',
    'Trinidad and Tobago': 'Trinidad and Tobago is the birthplace of the steelpan, a musical instrument created from oil drums. The country is also famous for its annual Carnival, one of the biggest and most colorful in the Caribbean.',
    'Tunisia': 'Tunisia is home to the ancient city of Carthage, once the center of the powerful Carthaginian Empire. The country\'s rich history includes periods of Roman, Arab, and Ottoman rule, making it a cultural crossroads in North Africa.',
    'Turkey': 'Turkey is a transcontinental country, with land in both Europe and Asia. It\'s known for its rich history, particularly the city of Istanbul (formerly Constantinople), which was the capital of both the Byzantine and Ottoman Empires.',
    'Turkmenistan': 'Turkmenistan is home to the Darvaza Gas Crater, also known as the "Door to Hell." This natural gas field has been burning continuously since it was accidentally ignited by Soviet engineers in 1971.',
    'Tuvalu': 'Tuvalu is one of the smallest and least populated countries in the world, consisting of nine tiny islands in the Pacific Ocean. The country is particularly vulnerable to rising sea levels due to climate change.',
    'Uganda': 'Uganda is known as the "Pearl of Africa" due to its stunning landscapes, which include lush forests, mountains, and lakes. The country is also home to over half of the world\'s remaining mountain gorillas, which can be seen in Bwindi Impenetrable National Park.',
    'Ukraine': 'Ukraine is the largest country entirely in Europe and is known for its rich cultural heritage and history. The country is also famous for its fertile land, often referred to as the "breadbasket of Europe" due to its extensive grain production.',
    'United Arab Emirates (UAE)': 'The UAE is home to the world\'s tallest building, the Burj Khalifa in Dubai, which stands at 828 meters (2,717 feet). The country is known for its rapid modernization and as a global hub for business and tourism.',
    'United Kingdom': 'The United Kingdom is famous for its royal family, with Buckingham Palace being one of the most iconic landmarks in London. The UK has a rich history and has significantly influenced global culture, politics, and economics.',
    'United States of America': 'The United States is one of the most diverse countries in the world, both culturally and geographically. It\'s known for iconic landmarks like the Statue of Liberty, the Grand Canyon, and its role as a global leader in science, technology, and entertainment.',
    'Uruguay': 'Uruguay is known for being one of the most progressive nations in Latin America, particularly in terms of social policies and democracy. The country is also famous for its beautiful beaches and for being the birthplace of the tango, a dance shared with Argentina.',
    'Uzbekistan': 'Uzbekistan is home to the ancient Silk Road cities of Samarkand, Bukhara, and Khiva, which were major centers of trade, culture, and learning. The country is known for its stunning Islamic architecture, including beautiful mosques and madrasas.',
    'Vanuatu': 'Vanuatu is known for its active volcanoes, including Mount Yasur on Tanna Island, which is one of the most accessible active volcanoes in the world. The country is also famous for its rich Melanesian culture and traditions.',
    'Vatican City': 'Vatican City is the smallest country in the world, both by area and population. It\'s the spiritual and administrative center of the Roman Catholic Church and home to the Pope. The Vatican Museums and St. Peter\'s Basilica are some of the most visited religious sites in the world.',
    'Venezuela': 'Venezuela is home to Angel Falls, the world\'s highest uninterrupted waterfall, with a height of 979 meters (3,212 feet). The country is also known for its vast oil reserves, which are among the largest in the world.',
    'Vietnam': 'Vietnam is famous for its beautiful landscapes, including the iconic terraced rice fields of the north and the limestone islands of Ha Long Bay. The country has a rich history, with influences from various cultures, including Chinese, French, and American.',
    'Yemen': 'Yemen is home to the ancient city of Sana\'a, one of the oldest continuously inhabited cities in the world, with a history that dates back over 2,500 years. The Old City of Sana\'a is a UNESCO World Heritage Site known for its unique architectural style with multi story buildings made of rammed earth.',
    'Zambia': 'Zambia is home to Victoria Falls, one of the largest and most famous waterfalls in the world, known locally as "Mosi oa Tunya," meaning "The Smoke That Thunders." The falls are a major attraction on the Zambezi River and are shared with neighboring Zimbabwe.',
    'Zimbabwe': 'Zimbabwe is known for the Great Zimbabwe Ruins, the remains of a medieval city that was once the capital of the Kingdom of Zimbabwe. The ruins are a UNESCO World Heritage Site and represent the largest ancient stone construction in sub Saharan Africa.'
};

const countryHints = {
    'Afghanistan': 'This country is known for its mountainous terrain and the historic Silk Road. It has been at the crossroads of trade and conquest for centuries.',
    'Albania': 'This small Balkan nation has a double-headed eagle on its red flag and is famous for its beautiful Adriatic and Ionian coastlines.',
    'Algeria': 'The largest country in Africa, this nation has vast stretches of the Sahara Desert and a capital city named Algiers.',
    'Andorra': 'A tiny country nestled in the Pyrenees Mountains between France and Spain, known for its ski resorts and duty-free shopping.',
    'Angola': 'Located in southern Africa, this country has rich oil reserves and the capital city of Luanda on the Atlantic Ocean.',
    'Antigua and Barbuda': 'This Caribbean country is known for having 365 beaches—one for every day of the year!',
    'Argentina': 'Famous for tango dancing, the Pampas, and its passionate love for soccer, this South American country has Buenos Aires as its capital.',
    'Armenia': 'This landlocked country in the Caucasus was the first to adopt Christianity as its state religion in 301 AD and is known for Mount Ararat.',
    'Australia': 'The only country that is also a continent, famous for kangaroos, the Great Barrier Reef, and the Sydney Opera House.',
    'Austria': 'Known for its classical music heritage, with famous composers like Mozart and Beethoven, this country has stunning Alpine landscapes and Vienna as its capital.',
    'Azerbaijan': 'Known as the "Land of Fire" because of its natural gas flames that burn continuously on the Absheron Peninsula, this country is on the Caspian Sea.',
    'Bahamas': 'A Caribbean country famous for its clear turquoise waters, vibrant coral reefs, and a swimming pigs attraction.',
    'Bahrain': 'A small island nation in the Persian Gulf known for its Formula 1 Grand Prix and pearl diving history.',
    'Bangladesh': 'A South Asian country famous for its dense population, river deltas, and the Sundarbans mangrove forest, home to Bengal tigers.',
    'Barbados': 'A Caribbean island known for its rum, flying fish, and being the birthplace of the singer Rihanna.',
    'Belarus': 'A landlocked Eastern European country known for its vast forests, the capital Minsk, and being a former Soviet republic.',
    'Belgium': 'Famous for its chocolates, waffles, and as the home of the European Union headquarters in Brussels.',
    'Belize': 'A Central American country known for its barrier reef, the Blue Hole, and being the only country in the region where English is the official language.',
    'Benin': 'A West African country known for its ancient Kingdom of Dahomey and vibrant voodoo culture.',
    'Bhutan': 'A small Himalayan kingdom known for its "Gross National Happiness" index and majestic monasteries like the Tiger\'s Nest.',
    'Bolivia': 'A South American country with the world\'s largest salt flat, Salar de Uyuni, and Lake Titicaca, the highest navigable lake in the world.',
    'Bosnia and Herzegovina': 'A Balkan country famous for its medieval bridges, such as the Stari Most in Mostar, and its diverse cultural heritage.',
    'Botswana': 'An African country known for the Okavango Delta, a vast inland delta teeming with wildlife, and being one of the world\'s largest diamond producers.',
    'Brazil': 'The largest country in South America, famous for the Amazon Rainforest, Rio Carnival, and being a soccer powerhouse.',
    'Brunei': 'A small, wealthy nation on the island of Borneo, known for its sultan and abundant oil reserves.',
    'Bulgaria': 'A Balkan country known for its roses, yogurt, and ancient Thracian sites.',
    'Burkina Faso': 'A West African country known for its music, film festival (FESPACO), and the capital, Ouagadougou.',
    'Burundi': 'A small landlocked country in East Africa known for its drumming culture and scenic Lake Tanganyika, one of the world\'s deepest lakes.',
    'Cabo Verde': 'An archipelago off the west coast of Africa, known for its Creole Portuguese-African culture, morna music, and beautiful volcanic islands.',
    'Cambodia': 'A Southeast Asian country famous for the ancient temple complex of Angkor Wat, one of the largest religious monuments in the world.',
    'Cameroon': 'An African country known as "Africa in Miniature" because it features many of the continent\'s major climates and ecosystems, from rainforests to deserts.',
    'Canada': 'The second-largest country in the world by land area, known for its maple syrup, ice hockey, and Niagara Falls.',
    'Central African Republic': 'A landlocked country in Central Africa known for its rainforests, pygmy tribes, and the Dzanga-Sangha National Park.',
    'Chad': 'An African country named after its largest lake, which is shrinking, and known for the Sahara Desert and the Tibesti Mountains.',
    'Chile': 'A long, narrow country in South America, famous for its Andes mountains, Atacama Desert, and Easter Island with its giant moai statues.',
    'China': 'The world\'s most populous country, known for its Great Wall, pandas, and being one of the world\'s oldest continuous civilizations.',
    'Colombia': 'A South American country known for its coffee, emeralds, and the vibrant city of Cartagena on the Caribbean coast.',
    'Comoros': 'A small island nation in the Indian Ocean, between Madagascar and the coast of Mozambique, known for its volcanic islands and vanilla production.',
    'Congo, Democratic Republic of the (DRC)': 'The largest country in sub-Saharan Africa, known for its rainforests, the Congo River, and mountain gorillas.',
    'Congo, Republic of the': 'A Central African country known for its rainforests, wildlife, and the capital city, Brazzaville, located across the river from Kinshasa, DRC.',
    'Costa Rica': 'A Central American country known for its biodiversity, ecotourism, and the phrase "Pura Vida" (Pure Life).',
    'Croatia': 'A European country famous for its stunning Adriatic coastline, numerous islands, and the medieval walled city of Dubrovnik.',
    'Cuba': 'A Caribbean island nation known for its cigars, classic cars, and its capital city, Havana.',
    'Cyprus': 'An island country in the eastern Mediterranean, known for its ancient ruins, divided capital (Nicosia), and being the mythical birthplace of Aphrodite.',
    'Czech Republic (Czechia)': 'A Central European country known for its medieval architecture, the city of Prague, and being one of the world\'s largest beer consumers.',
    'Denmark': 'A Scandinavian country known for its Viking history, being home to the original LEGOLAND, and the concept of "hygge," which means a cozy and comfortable lifestyle.',
    'Djibouti': 'A small country in the Horn of Africa known for its strategic location near the Red Sea and Gulf of Aden and Lake Assal, one of the saltiest bodies of water in the world.',
    'Dominica': 'A Caribbean island known as the "Nature Island" for its lush rainforests, hot springs, and the world\'s second-largest boiling lake.',
    'Dominican Republic': 'Occupies the eastern part of the island of Hispaniola, famous for its resorts, beautiful beaches, and being the first permanent European settlement in the Americas.',
    'East Timor (Timor-Leste)': 'A Southeast Asian country known for gaining independence in 2002 and its rich coffee plantations in the mountains.',
    'Ecuador': 'A South American country named after the equator, famous for the Galápagos Islands and the biodiversity that inspired Darwin\'s theory of evolution.',
    'Egypt': 'A North African country known for its ancient pyramids, the Great Sphinx, and the Nile River, the longest river in the world.',
    'El Salvador': 'The smallest and most densely populated country in Central America, known for its Pacific Ocean beaches and active volcanoes.',
    'Equatorial Guinea': 'The only African country where Spanish is the official language, known for its oil wealth and Bioko Island.',
    'Eritrea': 'A country in the Horn of Africa, known for its Italian colonial architecture in the capital, Asmara, a UNESCO World Heritage Site.',
    'Estonia': 'A Baltic state known for its digital advancements, medieval capital Tallinn, and having one of the world\'s fastest internet speeds.',
    'Eswatini (Swaziland)': 'A small landlocked African kingdom known for its rich cultural traditions and vibrant festivals like Umhlanga (Reed Dance).',
    'Ethiopia': 'A country in the Horn of Africa known as the birthplace of coffee, home to the ancient city of Lalibela and its rock-hewn churches.',
    'Fiji': 'A Pacific island nation known for its stunning beaches, clear lagoons, and as a top honeymoon destination.',
    'Finland': 'A Nordic country known for its thousands of lakes, saunas, and being one of the best places to see the Northern Lights.',
    'France': 'A European country famous for its Eiffel Tower, exquisite cuisine, art, fashion, and landmarks like the Louvre and Notre-Dame.',
    'Gabon': 'A country on the west coast of Central Africa known for its dense rainforests, low population density, and a vast network of national parks, including Loango National Park, famous for "surfing hippos."',
    'Gambia': 'The smallest country on mainland Africa, surrounded almost entirely by Senegal, known for the Gambia River that flows through its length.',
    'Georgia': 'A country located at the crossroads of Europe and Asia, known for its ancient winemaking tradition, with evidence of wine production dating back over 8,000 years.',
    'Germany': 'A European country known for its Oktoberfest, cars like BMW and Mercedes, and historical sites like the Berlin Wall and Neuschwanstein Castle.',
    'Ghana': 'A West African country known for its rich gold reserves, vibrant kente cloth, and historic slave forts like Cape Coast Castle.',
    'Greece': 'A European country known as the "cradle of Western civilization," famous for its ancient ruins like the Parthenon, beautiful islands, and delicious cuisine like feta cheese and olives.',
    'Grenada': 'A Caribbean island nation often called the "Island of Spice" because it is a leading producer of nutmeg and mace.',
    'Guatemala': 'A Central American country known for its ancient Maya city of Tikal and colorful indigenous markets like those in Chichicastenango.',
    'Guinea': 'A West African country rich in minerals, particularly bauxite, and known for the Fouta Djallon highlands and unique West African traditions.',
    'Guinea-Bissau': 'A small West African country known for the Bijagós Archipelago, a group of islands that is a UNESCO Biosphere Reserve.',
    'Guyana': 'The only English-speaking country in South America, known for its vast rainforests, Kaieteur Falls, and the unique blend of Caribbean and South American cultures.',
    'Haiti': 'A Caribbean country on the island of Hispaniola known for being the first independent black republic in the world and its vibrant art and culture, especially in Port-au-Prince.',
    'Honduras': 'A Central American country known for its ancient Maya ruins at Copán and its beautiful Caribbean beaches, including the Bay Islands, which are popular for scuba diving.',
    'Hungary': 'A Central European country known for its capital, Budapest, split by the Danube River, and famous for thermal baths and paprika-spiced dishes like goulash.',
    'Iceland': 'An island nation in the North Atlantic known as the "Land of Fire and Ice" due to its active volcanoes and glaciers, and for being one of the best places to see the Northern Lights.',
    'India': 'A South Asian country known for its diverse culture, the Taj Mahal, Bollywood, and being the birthplace of religions like Hinduism, Buddhism, Jainism, and Sikhism.',
    'Indonesia': 'The world\'s largest archipelago, consisting of over 17,000 islands, known for its Komodo dragons, orangutans in Borneo, and the famous island of Bali.',
    'Iran': 'A Middle Eastern country with a rich Persian heritage, known for its ancient ruins like Persepolis and its intricate carpets and Persian poetry.',
    'Iraq': 'A Middle Eastern country known for its ancient Mesopotamian history, often referred to as the "Cradle of Civilization," where the cities of Babylon and Ur were located.',
    'Ireland': 'An island nation in the North Atlantic known as the "Emerald Isle" for its lush green landscapes, rich folklore with leprechauns, and St. Patrick\'s Day celebrations.',
    'Italy': 'A European country known for its boot-shaped peninsula, its ancient Roman ruins like the Colosseum, and its delicious cuisine, including pasta and pizza.',
    'Jamaica': 'A Caribbean island nation known as the birthplace of reggae music and Bob Marley, beautiful beaches, and the Blue Mountains.',
    'Japan': 'An East Asian country known for its unique blend of ancient traditions and modern technology, including samurai, sushi, anime, and Mount Fuji.',
    'Jordan': 'A Middle Eastern country famous for the ancient city of Petra, carved into rose-red cliffs, and the Dead Sea, one of the saltiest bodies of water on Earth.',
    'Kazakhstan': 'The world\'s largest landlocked country, known for its vast steppes and as the location of the Baikonur Cosmodrome, where the first human, Yuri Gagarin, was launched into space.',
    'Kenya': 'An East African country famous for its savannas, wildlife safaris in the Maasai Mara, and being home to Mount Kenya, Africa\'s second-highest peak.',
    'Kiribati': 'A Pacific island nation spread over 33 atolls, known for being one of the first countries to greet the new year due to its location along the International Date Line.',
    'Korea, North (North Korea)': 'A secretive country known for its strict government, mass games, and the Demilitarized Zone (DMZ) that separates it from its southern neighbor.',
    'Korea, South (South Korea)': 'An East Asian country known for its high-tech cities like Seoul, global K-pop culture, and delicious food like kimchi and bulgogi.',
    'Kuwait': 'A small, oil-rich country in the Persian Gulf, known for its modern skyscrapers, the Kuwait Towers, and the invasion that led to the Gulf War in 1990.',
    'Kyrgyzstan': 'A Central Asian country known for its dramatic mountainous terrain, nomadic traditions, and hosting the World Nomad Games.',
    'Laos': 'A landlocked Southeast Asian country known for its Buddhist monasteries, the ancient city of Luang Prabang, and the Mekong River.',
    'Latvia': 'A Baltic state known for its capital, Riga, with its stunning Art Nouveau architecture, and for its rich forests and beautiful beaches along the Baltic Sea.',
    'Lebanon': 'A Middle Eastern country known for its historical ruins like those in Baalbek, its cuisine (such as hummus and falafel), and its cosmopolitan capital, Beirut.',
    'Lesotho': 'A small landlocked kingdom entirely surrounded by South Africa, known for its high altitude—being the only country in the world entirely above 1,000 meters (3,281 feet).',
    'Liberia': 'A West African country founded by freed American slaves, known for having Africa\'s first female president and being one of the few countries in Africa never colonized.',
    'Libya': 'A North African country known for its vast desert landscapes, ancient Greek and Roman ruins, and the capital city of Tripoli.',
    'Liechtenstein': 'A tiny European principality nestled between Switzerland and Austria, known for its alpine scenery, castles, and being one of the world\'s smallest and wealthiest countries.',
    'Lithuania': 'A Baltic country known for being the first Soviet republic to declare independence, its medieval capital Vilnius, and its beautiful sand dunes on the Curonian Spit.',
    'Luxembourg': 'A small, landlocked European country known for its wealthy economy, being one of the three capitals of the European Union, and its impressive medieval fortifications.',
    'Madagascar': 'An island nation off the southeast coast of Africa, known for its unique wildlife, especially lemurs, and the distinctive baobab trees.',
    'Malawi': 'A landlocked country in southeastern Africa known as the "Warm Heart of Africa" and for Lake Malawi, one of the deepest and most biodiverse lakes in the world.',
    'Malaysia': 'A Southeast Asian country known for its modern capital Kuala Lumpur, the Petronas Towers, and its diverse culture mixing Malay, Chinese, and Indian influences.',
    'Maldives': 'A tropical paradise in the Indian Ocean, famous for its stunning coral atolls, overwater bungalows, and being the world\'s lowest-lying country.',
    'Mali': 'A West African country known for the ancient city of Timbuktu, once a major center of Islamic learning and trade, and its vibrant music scene.',
    'Malta': 'A small island nation in the Mediterranean, known for its rich history with ancient temples older than the pyramids, and the fortified capital city, Valletta.',
    'Marshall Islands': 'A Pacific island nation, known for its WWII history and the nuclear testing that took place at Bikini Atoll.',
    'Mauritania': 'A West African country known for its vast Sahara Desert landscapes, ancient caravan cities like Chinguetti, and the eye-catching Richat Structure, also known as the "Eye of the Sahara."',
    'Mauritius': 'An island nation in the Indian Ocean, known for its beaches, reefs, and the now-extinct dodo bird, which was native to the island.',
    'Mexico': 'A North American country famous for its rich cultural heritage, including Aztec and Maya ruins, vibrant festivals like Día de los Muertos, and its diverse cuisine with tacos, enchiladas, and mole.',
    'Micronesia': 'A group of islands in the Pacific Ocean, known for its stunning marine biodiversity and the ancient city of Nan Madol, built on artificial islands.',
    'Moldova': 'A small landlocked country in Eastern Europe known for its wine, particularly from the Mileștii Mici winery, which has the largest wine collection in the world.',
    'Monaco': 'The second smallest country in the world, known for its luxury casinos, the Monaco Grand Prix, and being a playground for the rich and famous on the French Riviera.',
    'Mongolia': 'A vast landlocked country in Central Asia, known for its nomadic culture, the Gobi Desert, and being the birthplace of Genghis Khan.',
    'Montenegro': 'A Balkan country known for its stunning Adriatic coastline, medieval towns like Kotor, and rugged mountainous terrain.',
    'Morocco': 'A North African country known for its colorful markets, ancient medinas like in Marrakech, and the Atlas Mountains.',
    'Mozambique': 'A southeastern African country known for its beautiful Indian Ocean coastline, vibrant culture, and the unique island of Mozambique, a UNESCO World Heritage Site.',
    'Myanmar (Burma)': 'A Southeast Asian country known for its ancient city of Bagan, dotted with thousands of Buddhist temples, and the Shwedagon Pagoda in Yangon.',
    'Namibia': 'A country in southwestern Africa known for the Namib Desert, one of the oldest deserts in the world, and its towering red sand dunes in Sossusvlei.',
    'Nauru': 'The third smallest country in the world by land area, located in the Pacific Ocean, known for its phosphate mining and having no official capital.',
    'Nepal': 'A South Asian country famous for Mount Everest, the highest peak in the world, and being the birthplace of Buddha in Lumbini.',
    'Netherlands': 'A European country known for its iconic windmills, tulip fields, canals in Amsterdam, and being one of the world\'s lowest-lying countries.',
    'New Zealand': 'A Pacific island nation known for its stunning landscapes featured in "The Lord of the Rings" movies, indigenous Maori culture, and adventure sports like bungee jumping.',
    'Nicaragua': 'A Central American country known for its large freshwater lakes, Lake Nicaragua and Lake Managua, and its numerous volcanoes, including Cerro Negro, where volcano boarding is a popular activity.',
    'Niger': 'A landlocked West African country known for the Sahara Desert and the ancient trading city of Agadez.',
    'Nigeria': 'The most populous country in Africa, known for its Nollywood film industry, Afrobeat music, and vibrant city of Lagos.',
    'North Macedonia': 'A Balkan country known for its rich history, Ohrid Lake, and being the birthplace of Alexander the Great.',
    'Norway': 'A Scandinavian country known for its stunning fjords, Northern Lights, and being one of the happiest countries in the world.',
    'Oman': 'A Middle Eastern country known for its historic forts, the bustling souks of Muscat, and the frankincense trade that dates back thousands of years.',
    'Pakistan': 'A South Asian country known for its majestic mountain ranges, including K2, the second-highest peak in the world, and its rich history with ancient sites like Mohenjo-Daro.',
    'Palau': 'A Pacific island nation famous for its stunning marine environment, including Jellyfish Lake, where you can swim among thousands of harmless jellyfish.',
    'Palestine': 'A region in the Middle East known for its historical and religious significance, particularly the cities of Bethlehem and Jerusalem, which are sacred to Jews, Christians, and Muslims.',
    'Panama': 'A Central American country known for the Panama Canal, a vital shortcut for global maritime trade that connects the Atlantic and Pacific Oceans.',
    'Papua New Guinea': 'An island nation in Oceania known for its incredible cultural diversity, with over 800 languages spoken, and its dense rainforests and unique wildlife.',
    'Paraguay': 'A landlocked South American country known for its large rivers, the Itaipu Dam (one of the world\'s largest hydroelectric plants), and its bilingual culture (Spanish and Guarani).',
    'Peru': 'A South American country famous for the ancient Inca city of Machu Picchu, high in the Andes Mountains, and for the vibrant culture of the indigenous Quechua people.',
    'Philippines': 'A Southeast Asian archipelago consisting of over 7,000 islands, known for its beautiful beaches, rice terraces, and vibrant festivals like Sinulog and Ati-Atihan.',
    'Poland': 'A European country known for its medieval castles, the historic city of Kraków, and the Auschwitz-Birkenau concentration camp memorial.',
    'Portugal': 'A European country known for its maritime explorers, stunning coastal cliffs, and the production of port wine in the Douro Valley.',
    'Qatar': 'A small, wealthy country in the Middle East known for its futuristic skyscrapers, hosting the 2022 FIFA World Cup, and its vast natural gas reserves.',
    'Romania': 'A European country known for the legend of Dracula, medieval castles like Bran Castle, and the scenic Carpathian Mountains.',
    'Russia': 'The largest country in the world, spanning Europe and Asia, known for its vast Siberian wilderness, the Red Square in Moscow, and its rich cultural history.',
    'Rwanda': 'An East African country known as the "Land of a Thousand Hills" for its mountainous terrain, and for its mountain gorillas, which can be seen in Volcanoes National Park.',
    'Saint Kitts and Nevis': 'The smallest country in the Western Hemisphere, consisting of two main islands, known for its sugar plantations and scenic railway tours.',
    'Saint Lucia': 'A Caribbean island nation known for its iconic twin peaks, the Pitons, and the world\'s only drive-in volcano.',
    'Saint Vincent and the Grenadines': 'A Caribbean nation consisting of one main island and several smaller ones, known for its pristine beaches and filming locations for "Pirates of the Caribbean."',
    'Samoa': 'A Pacific island country known for its traditional culture called "fa\'a Samoa," spectacular waterfalls, and the To Sua Ocean Trench, a famous natural swimming hole.',
    'San Marino': 'A tiny landlocked country surrounded by Italy, known for being one of the world\'s oldest republics and its medieval fortresses perched on Mount Titano.',
    'Sao Tome and Principe': 'A small island nation in the Gulf of Guinea, known for its cocoa plantations, unique biodiversity, and beautiful volcanic landscapes.',
    'Saudi Arabia': 'A Middle Eastern country known for being the birthplace of Islam, housing the holy cities of Mecca and Medina, and its vast desert landscapes.',
    'Senegal': 'A West African country known for its vibrant music scene, especially mbalax, the Pink Lake (Lake Retba), and the historic slave trade island of Gorée.',
    'Serbia': 'A Balkan country known for its capital, Belgrade, lively festivals, and historical monasteries scattered throughout the country.',
    'Seychelles': 'An archipelago in the Indian Ocean known for its stunning beaches, unique granite rock formations, and rich marine life, making it a top honeymoon destination.',
    'Sierra Leone': 'A West African country known for its beautiful beaches, diamond mines, and being one of the countries with the highest biodiversity in Africa.',
    'Singapore': 'A city-state in Southeast Asia known for its rapid development, modern skyline with Marina Bay Sands, strict laws, and multicultural society.',
    'Slovakia': 'A Central European country known for its dramatic mountain ranges, medieval castles, and the charming old town of Bratislava, its capital.',
    'Slovenia': 'A small European country known for its picturesque Lake Bled, stunning caves like Postojna, and being one of the greenest countries in the world.',
    'Solomon Islands': 'A Pacific nation known for its World War II history, especially the Battle of Guadalcanal, and beautiful coral reefs.',
    'Somalia': 'An East African country with the longest coastline on mainland Africa, known for its ancient maritime trade history and cultural traditions like poetry.',
    'South Africa': 'A country on the southern tip of Africa known for its diverse landscapes, from safaris in Kruger National Park to the vibrant city of Cape Town and its symbol of the anti-apartheid struggle, Nelson Mandela.',
    'South Korea': 'An East Asian country known for its high-tech cities like Seoul, the global phenomenon of K-pop, and its delicious cuisine like kimchi and bulgogi.',
    'South Sudan': 'The world\'s youngest country, gaining independence from Sudan in 2011, known for its rich cultural diversity and the vast Sudd swamp.',
    'Spain': 'A European country known for its flamenco dance, tapas, vibrant festivals like La Tomatina and Running of the Bulls, and landmarks like the Alhambra and Sagrada Família.',
    'Sri Lanka': 'An island nation in the Indian Ocean known as the "Pearl of the Indian Ocean," famous for its ancient temples, tea plantations, and diverse wildlife.',
    'Sudan': 'A North African country known for its ancient pyramids in Meroë, along the Nile River, and its long history that intersects with that of ancient Egypt.',
    'Suriname': 'The smallest country in South America, known for its tropical rainforests, multicultural society, and Dutch colonial architecture.',
    'Sweden': 'A Scandinavian country known for its high standard of living, beautiful landscapes with thousands of lakes, and being the birthplace of brands like IKEA and Volvo.',
    'Switzerland': 'A landlocked European country famous for its Alps, precision watches, chocolate, and neutrality in international conflicts.',
    'Syria': 'A Middle Eastern country with a rich history dating back to ancient civilizations, known for its historic cities like Damascus and Palmyra.',
    'Taiwan': 'An island off the coast of China, known for its vibrant night markets, bubble tea, and being one of the world\'s top producers of semiconductors.',
    'Tajikistan': 'A Central Asian country known for its stunning Pamir Mountains, often called the "Roof of the World," and its Silk Road heritage.',
    'Tanzania': 'An East African country famous for Mount Kilimanjaro, Africa\'s highest peak, and the Serengeti National Park, known for the Great Migration of wildebeest.',
    'Thailand': 'A Southeast Asian country known for its beautiful beaches, vibrant street food culture, and temples like Wat Phra Kaew in Bangkok.',
    'Togo': 'A small West African country known for its palm-lined beaches, hilltop villages, and the UNESCO World Heritage site Koutammakou, the Land of the Batammariba.',
    'Tonga': 'A Polynesian kingdom of more than 170 South Pacific islands, known for its rich cultural traditions and being the only monarchy in the Pacific.',
    'Trinidad and Tobago': 'A Caribbean nation known for its annual Carnival, steelpan music, and diverse wildlife, including the world\'s largest brain coral.',
    'Tunisia': 'A North African country known for its ancient ruins like Carthage, the desert landscapes of the Sahara, and its role in the "Arab Spring" revolutions.',
    'Turkey': 'A country that straddles Europe and Asia, known for its rich history in cities like Istanbul (formerly Constantinople), the Hagia Sophia, and unique landscapes like Cappadocia.',
    'Turkmenistan': 'A Central Asian country known for its vast deserts, the ancient Silk Road city of Merv, and the Darvaza Gas Crater, also known as the "Door to Hell."',
    'Tuvalu': 'One of the smallest and least populated countries in the world, located in the Pacific Ocean and known for its vulnerability to rising sea levels due to climate change.',
    'Uganda': 'An East African country known as the "Pearl of Africa," famous for its mountain gorillas in Bwindi Impenetrable National Park and the source of the Nile River.',
    'Ukraine': 'A large Eastern European country known for its vast wheat fields (earning it the nickname "breadbasket of Europe"), rich cultural heritage, and historic cities like Kyiv.',
    'United Arab Emirates (UAE)': 'A Middle Eastern country known for its ultra-modern skyscrapers, luxury shopping, and iconic landmarks like the Burj Khalifa in Dubai, the world\'s tallest building.',
    'United Kingdom (UK)': 'A European country made up of England, Scotland, Wales, and Northern Ireland, known for its royal family, historical landmarks like Buckingham Palace and Stonehenge, and being the birthplace of Shakespeare.',
    'United States of America': 'A large and diverse country in North America known for its global cultural influence, iconic landmarks like the Statue of Liberty, the Grand Canyon, and Hollywood.',
    'Uruguay': 'A South American country known for its beach-lined coast, the laid-back capital Montevideo, and being one of the first countries in the world to legalize recreational cannabis.',
    'Uzbekistan': 'A Central Asian country known for its Silk Road cities like Samarkand, Bukhara, and Khiva, famous for their stunning Islamic architecture and ancient mosques.',
    'Vanuatu': 'A Pacific island nation known for its active volcanoes, traditional Melanesian culture, and unique land diving ritual called "naghol," which is a precursor to modern bungee jumping.',
    'Vatican City': 'The smallest country in the world, located within Rome, Italy, and known as the spiritual and administrative center of the Roman Catholic Church, where the Pope resides.',
    'Venezuela': 'A South American country known for Angel Falls, the world\'s highest uninterrupted waterfall, and its vast oil reserves.',
    'Vietnam': 'A Southeast Asian country famous for its vibrant cities like Hanoi and Ho Chi Minh City, delicious street food like pho and banh mi, and scenic landscapes such as Ha Long Bay.',
    'Yemen': 'A Middle Eastern country known for its ancient city of Sana\'a, a UNESCO World Heritage Site, and the unique terraced fields and mud-brick skyscrapers of Shibam.',
    'Zambia': 'A landlocked country in Southern Africa known for Victoria Falls, one of the largest and most famous waterfalls in the world, shared with Zimbabwe.',
    'Zimbabwe': 'A Southern African country known for the Great Zimbabwe Ruins, an ancient city that was the capital of the Kingdom of Zimbabwe, and also for its side of Victoria Falls.',
}

// Export the variables
export { countries, countryToCode, countryFacts, countryHints };