# Dictionary containing facts about countries
countryFacts = {
    'Afghanistan': 'This country is known for its mountainous terrain and the historic Silk Road. It has been at the crossroads of trade and conquest for centuries.',
    'Albania': 'This small Balkan nation has a double-headed eagle on its red flag and is famous for its beautiful Adriatic and Ionian coastlines.',
    'Algeria': 'The largest country in Africa, this nation has vast stretches of the Sahara Desert and a capital city named Algiers.',
    'Andorra': 'A tiny country nestled in the Pyrenees Mountains between France and Spain, known for its ski resorts and duty-free shopping.',
    'Angola': 'Located in southern Africa, this country has rich oil reserves and the capital city of Luanda on the Atlantic Ocean.',
    'Antigua and Barbuda': 'This Caribbean country is known for having 365 beaches—one for every day of the year!',
    'Argentina': 'Famous for tango dancing, the Pampas, and its passionate love for soccer, this South American country has Buenos Aires as its capital.',
    'Armenia': 'This landlocked country in the Caucasus was the first to adopt Christianity as its state religion in 301 AD and is known for Mount Ararat.',
    'Australia': 'The only country that is also a continent, famous for kangaroos, the Great Barrier Reef, and the Sydney Opera House.',
    'Austria': 'Known for its classical music heritage, with famous composers like Mozart and Beethoven, this country has stunning Alpine landscapes and Vienna as its capital.',
    'Azerbaijan': 'Known as the "Land of Fire" because of its natural gas flames that burn continuously on the Absheron Peninsula, this country is on the Caspian Sea.',
    'Bahamas': 'A Caribbean country famous for its clear turquoise waters, vibrant coral reefs, and a swimming pigs attraction.',
    'Bahrain': 'A small island nation in the Persian Gulf known for its Formula 1 Grand Prix and pearl diving history.',
    'Bangladesh': 'A South Asian country famous for its dense population, river deltas, and the Sundarbans mangrove forest, home to Bengal tigers.',
    'Barbados': 'A Caribbean island known for its rum, flying fish, and being the birthplace of the singer Rihanna.',
    'Belarus': 'A landlocked Eastern European country known for its vast forests, the capital Minsk, and being a former Soviet republic.',
    'Belgium': 'Famous for its chocolates, waffles, and as the home of the European Union headquarters in Brussels.',
    'Belize': 'A Central American country known for its barrier reef, the Blue Hole, and being the only country in the region where English is the official language.',
    'Benin': 'A West African country known for its ancient Kingdom of Dahomey and vibrant voodoo culture.',
    'Bhutan': 'A small Himalayan kingdom known for its "Gross National Happiness" index and majestic monasteries like the Tiger\'s Nest.',
    'Bolivia': 'A South American country with the world\'s largest salt flat, Salar de Uyuni, and Lake Titicaca, the highest navigable lake in the world.',
    'Bosnia and Herzegovina': 'A Balkan country famous for its medieval bridges, such as the Stari Most in Mostar, and its diverse cultural heritage.',
    'Botswana': 'An African country known for the Okavango Delta, a vast inland delta teeming with wildlife, and being one of the world\'s largest diamond producers.',
    'Brazil': 'The largest country in South America, famous for the Amazon Rainforest, Rio Carnival, and being a soccer powerhouse.',
    'Brunei': 'A small, wealthy nation on the island of Borneo, known for its sultan and abundant oil reserves.',
    'Bulgaria': 'A Balkan country known for its roses, yogurt, and ancient Thracian sites.',
    'Burkina Faso': 'A West African country known for its music, film festival (FESPACO), and the capital, Ouagadougou.',
    'Burundi': 'A small landlocked country in East Africa known for its drumming culture and scenic Lake Tanganyika, one of the world\'s deepest lakes.',
    'Cape Verde': 'An archipelago off the west coast of Africa, known for its Creole Portuguese-African culture, morna music, and beautiful volcanic islands.',
    'Cambodia': 'A Southeast Asian country famous for the ancient temple complex of Angkor Wat, one of the largest religious monuments in the world.',
    'Cameroon': 'An African country known as "Africa in Miniature" because it features many of the continent\'s major climates and ecosystems, from rainforests to deserts.',
    'Canada': 'The second-largest country in the world by land area, known for its maple syrup, ice hockey, and Niagara Falls.',
    'Central African Republic': 'A landlocked country in Central Africa known for its rainforests, pygmy tribes, and the Dzanga-Sangha National Park.',
    'Chad': 'An African country named after its largest lake, which is shrinking, and known for the Sahara Desert and the Tibesti Mountains.',
    'Chile': 'A long, narrow country in South America, famous for its Andes mountains, Atacama Desert, and Easter Island with its giant moai statues.',
    'China': 'The world\'s most populous country, known for its Great Wall, pandas, and being one of the world\'s oldest continuous civilizations.',
    'Colombia': 'A South American country known for its coffee, emeralds, and the vibrant city of Cartagena on the Caribbean coast.',
    'Comoros': 'A small island nation in the Indian Ocean, between Madagascar and the coast of Mozambique, known for its volcanic islands and vanilla production.',
    'Congo, Democratic Republic of the (DRC)': 'The largest country in sub-Saharan Africa, known for its rainforests, the Congo River, and mountain gorillas.',
    'Congo, Republic of the': 'A Central African country known for its rainforests, wildlife, and the capital city, Brazzaville, located across the river from Kinshasa, DRC.',
    'Costa Rica': 'A Central American country known for its biodiversity, ecotourism, and the phrase "Pura Vida" (Pure Life).',
    'Croatia': 'A European country famous for its stunning Adriatic coastline, numerous islands, and the medieval walled city of Dubrovnik.',
    'Cuba': 'A Caribbean island nation known for its cigars, classic cars, and its capital city, Havana.',
    'Cyprus': 'An island country in the eastern Mediterranean, known for its ancient ruins, divided capital (Nicosia), and being the mythical birthplace of Aphrodite.',
    'Czech Republic (Czechia)': 'A Central European country known for its medieval architecture, the city of Prague, and being one of the world\'s largest beer consumers.',
    'Denmark': 'A Scandinavian country known for its Viking history, being home to the original LEGOLAND, and the concept of "hygge," which means a cozy and comfortable lifestyle.',
    'Djibouti': 'A small country in the Horn of Africa known for its strategic location near the Red Sea and Gulf of Aden and Lake Assal, one of the saltiest bodies of water in the world.',
    'Dominica': 'A Caribbean island known as the "Nature Island" for its lush rainforests, hot springs, and the world\'s second-largest boiling lake.',
    'Dominican Republic': 'Occupies the eastern part of the island of Hispaniola, famous for its resorts, beautiful beaches, and being the first permanent European settlement in the Americas.',
    'East Timor (Timor-Leste)': 'A Southeast Asian country known for gaining independence in 2002 and its rich coffee plantations in the mountains.',
    'Ecuador': 'A South American country named after the equator, famous for the Galápagos Islands and the biodiversity that inspired Darwin\'s theory of evolution.',
    'Egypt': 'A North African country known for its ancient pyramids, the Great Sphinx, and the Nile River, the longest river in the world.',
    'El Salvador': 'The smallest and most densely populated country in Central America, known for its Pacific Ocean beaches and active volcanoes.',
    'Equatorial Guinea': 'The only African country where Spanish is the official language, known for its oil wealth and Bioko Island.',
    'Eritrea': 'A country in the Horn of Africa, known for its Italian colonial architecture in the capital, Asmara, a UNESCO World Heritage Site.',
    'Estonia': 'A Baltic state known for its digital advancements, medieval capital Tallinn, and having one of the world\'s fastest internet speeds.',
    'Eswatini (Swaziland)': 'A small landlocked African kingdom known for its rich cultural traditions and vibrant festivals like Umhlanga (Reed Dance).',
    'Ethiopia': 'A country in the Horn of Africa known as the birthplace of coffee, home to the ancient city of Lalibela and its rock-hewn churches.',
    'Fiji': 'A Pacific island nation known for its stunning beaches, clear lagoons, and as a top honeymoon destination.',
    'Finland': 'A Nordic country known for its thousands of lakes, saunas, and being one of the best places to see the Northern Lights.',
    'France': 'A European country famous for its Eiffel Tower, exquisite cuisine, art, fashion, and landmarks like the Louvre and Notre-Dame.',
    'Gabon': 'A country on the west coast of Central Africa known for its dense rainforests, low population density, and a vast network of national parks, including Loango National Park, famous for "surfing hippos."',
    'Gambia': 'The smallest country on mainland Africa, surrounded almost entirely by Senegal, known for the Gambia River that flows through its length.',
    'Georgia': 'A country located at the crossroads of Europe and Asia, known for its ancient winemaking tradition, with evidence of wine production dating back over 8,000 years.',
    'Germany': 'A European country known for its Oktoberfest, cars like BMW and Mercedes, and historical sites like the Berlin Wall and Neuschwanstein Castle.',
    'Ghana': 'A West African country known for its rich gold reserves, vibrant kente cloth, and historic slave forts like Cape Coast Castle.',
    'Greece': 'A European country known as the "cradle of Western civilization," famous for its ancient ruins like the Parthenon, beautiful islands, and delicious cuisine like feta cheese and olives.',
    'Grenada': 'A Caribbean island nation often called the "Island of Spice" because it is a leading producer of nutmeg and mace.',
    'Guatemala': 'A Central American country known for its ancient Maya city of Tikal and colorful indigenous markets like those in Chichicastenango.',
    'Guinea': 'A West African country rich in minerals, particularly bauxite, and known for the Fouta Djallon highlands and unique West African traditions.',
    'Guinea-Bissau': 'A small West African country known for the Bijagós Archipelago, a group of islands that is a UNESCO Biosphere Reserve.',
    'Guyana': 'The only English-speaking country in South America, known for its vast rainforests, Kaieteur Falls, and the unique blend of Caribbean and South American cultures.',
    'Haiti': 'A Caribbean country on the island of Hispaniola known for being the first independent black republic in the world and its vibrant art and culture, especially in Port-au-Prince.',
    'Honduras': 'A Central American country known for its ancient Maya ruins at Copán and its beautiful Caribbean beaches, including the Bay Islands, which are popular for scuba diving.',
    'Hungary': 'A Central European country known for its capital, Budapest, split by the Danube River, and famous for thermal baths and paprika-spiced dishes like goulash.',
    'Iceland': 'An island nation in the North Atlantic known as the "Land of Fire and Ice" due to its active volcanoes and glaciers, and for being one of the best places to see the Northern Lights.',
    'India': 'A South Asian country known for its diverse culture, the Taj Mahal, Bollywood, and being the birthplace of religions like Hinduism, Buddhism, Jainism, and Sikhism.',
    'Indonesia': 'The world\'s largest archipelago, consisting of over 17,000 islands, known for its Komodo dragons, orangutans in Borneo, and the famous island of Bali.',
    'Iran': 'A Middle Eastern country with a rich Persian heritage, known for its ancient ruins like Persepolis and its intricate carpets and Persian poetry.',
    'Iraq': 'A Middle Eastern country known for its ancient Mesopotamian history, often referred to as the "Cradle of Civilization," where the cities of Babylon and Ur were located.',
    'Ireland': 'An island nation in the North Atlantic known as the "Emerald Isle" for its lush green landscapes, rich folklore with leprechauns, and St. Patrick\'s Day celebrations.',
    'Italy': 'A European country known for its boot-shaped peninsula, its ancient Roman ruins like the Colosseum, and its delicious cuisine, including pasta and pizza.',
    'Jamaica': 'A Caribbean island nation known as the birthplace of reggae music and Bob Marley, beautiful beaches, and the Blue Mountains.',
    'Japan': 'An East Asian country known for its unique blend of ancient traditions and modern technology, including samurai, sushi, anime, and Mount Fuji.',
    'Jordan': 'A Middle Eastern country famous for the ancient city of Petra, carved into rose-red cliffs, and the Dead Sea, one of the saltiest bodies of water on Earth.',
    'Kazakhstan': 'The world\'s largest landlocked country, known for its vast steppes and as the location of the Baikonur Cosmodrome, where the first human, Yuri Gagarin, was launched into space.',
    'Kenya': 'An East African country famous for its savannas, wildlife safaris in the Maasai Mara, and being home to Mount Kenya, Africa\'s second-highest peak.',
    'Kiribati': 'A Pacific island nation spread over 33 atolls, known for being one of the first countries to greet the new year due to its location along the International Date Line.',
    'North Korea': 'A secretive country known for its strict government, mass games, and the Demilitarized Zone (DMZ) that separates it from its southern neighbor.',
    'South Korea': 'An East Asian country known for its high-tech cities like Seoul, global K-pop culture, and delicious food like kimchi and bulgogi.',
    'Kuwait': 'A small, oil-rich country in the Persian Gulf, known for its modern skyscrapers, the Kuwait Towers, and the invasion that led to the Gulf War in 1990.',
    'Kyrgyzstan': 'A Central Asian country known for its dramatic mountainous terrain, nomadic traditions, and hosting the World Nomad Games.',
    'Laos': 'A landlocked Southeast Asian country known for its Buddhist monasteries, the ancient city of Luang Prabang, and the Mekong River.',
    'Latvia': 'A Baltic state known for its capital, Riga, with its stunning Art Nouveau architecture, and for its rich forests and beautiful beaches along the Baltic Sea.',
    'Lebanon': 'A Middle Eastern country known for its historical ruins like those in Baalbek, its cuisine (such as hummus and falafel), and its cosmopolitan capital, Beirut.',
    'Lesotho': 'A small landlocked kingdom entirely surrounded by South Africa, known for its high altitude—being the only country in the world entirely above 1,000 meters (3,281 feet).',
    'Liberia': 'A West African country founded by freed American slaves, known for having Africa\'s first female president and being one of the few countries in Africa never colonized.',
    'Libya': 'A North African country known for its vast desert landscapes, ancient Greek and Roman ruins, and the capital city of Tripoli.',
    'Liechtenstein': 'A tiny European principality nestled between Switzerland and Austria, known for its alpine scenery, castles, and being one of the world\'s smallest and wealthiest countries.',
    'Lithuania': 'A Baltic country known for being the first Soviet republic to declare independence, its medieval capital Vilnius, and its beautiful sand dunes on the Curonian Spit.',
    'Luxembourg': 'A small, landlocked European country known for its wealthy economy, being one of the three capitals of the European Union, and its impressive medieval fortifications.',
    'Madagascar': 'An island nation off the southeast coast of Africa, known for its unique wildlife, especially lemurs, and the distinctive baobab trees.',
    'Malawi': 'A landlocked country in southeastern Africa known as the "Warm Heart of Africa" and for Lake Malawi, one of the deepest and most biodiverse lakes in the world.',
    'Malaysia': 'A Southeast Asian country known for its modern capital Kuala Lumpur, the Petronas Towers, and its diverse culture mixing Malay, Chinese, and Indian influences.',
    'Maldives': 'A tropical paradise in the Indian Ocean, famous for its stunning coral atolls, overwater bungalows, and being the world\'s lowest-lying country.',
    'Mali': 'A West African country known for the ancient city of Timbuktu, once a major center of Islamic learning and trade, and its vibrant music scene.',
    'Malta': 'A small island nation in the Mediterranean, known for its rich history with ancient temples older than the pyramids, and the fortified capital city, Valletta.',
    'Marshall Islands': 'A Pacific island nation, known for its WWII history and the nuclear testing that took place at Bikini Atoll.',
    'Mauritania': 'A West African country known for its vast Sahara Desert landscapes, ancient caravan cities like Chinguetti, and the eye-catching Richat Structure, also known as the "Eye of the Sahara."',
    'Mauritius': 'An island nation in the Indian Ocean, known for its beaches, reefs, and the now-extinct dodo bird, which was native to the island.',
    'Mexico': 'A North American country famous for its rich cultural heritage, including Aztec and Maya ruins, vibrant festivals like Día de los Muertos, and its diverse cuisine with tacos, enchiladas, and mole.',
    'Micronesia': 'A group of islands in the Pacific Ocean, known for its stunning marine biodiversity and the ancient city of Nan Madol, built on artificial islands.',
    'Moldova': 'A small landlocked country in Eastern Europe known for its wine, particularly from the Mileștii Mici winery, which has the largest wine collection in the world.',
    'Monaco': 'The second smallest country in the world, known for its luxury casinos, the Monaco Grand Prix, and being a playground for the rich and famous on the French Riviera.',
    'Mongolia': 'A vast landlocked country in Central Asia, known for its nomadic culture, the Gobi Desert, and being the birthplace of Genghis Khan.',
    'Montenegro': 'A Balkan country known for its stunning Adriatic coastline, medieval towns like Kotor, and rugged mountainous terrain.',
    'Morocco': 'A North African country known for its colorful markets, ancient medinas like in Marrakech, and the Atlas Mountains.',
    'Mozambique': 'A southeastern African country known for its beautiful Indian Ocean coastline, vibrant culture, and the unique island of Mozambique, a UNESCO World Heritage Site.',
    'Myanmar (Burma)': 'A Southeast Asian country known for its ancient city of Bagan, dotted with thousands of Buddhist temples, and the Shwedagon Pagoda in Yangon.',
    'Namibia': 'A country in southwestern Africa known for the Namib Desert, one of the oldest deserts in the world, and its towering red sand dunes in Sossusvlei.',
    'Nauru': 'The third smallest country in the world by land area, located in the Pacific Ocean, known for its phosphate mining and having no official capital.',
    'Nepal': 'A South Asian country famous for Mount Everest, the highest peak in the world, and being the birthplace of Buddha in Lumbini.',
    'Netherlands': 'A European country known for its iconic windmills, tulip fields, canals in Amsterdam, and being one of the world\'s lowest-lying countries.',
    'New Zealand': 'A Pacific island nation known for its stunning landscapes featured in "The Lord of the Rings" movies, indigenous Maori culture, and adventure sports like bungee jumping.',
    'Nicaragua': 'A Central American country known for its large freshwater lakes, Lake Nicaragua and Lake Managua, and its numerous volcanoes, including Cerro Negro, where volcano boarding is a popular activity.',
    'Niger': 'A landlocked West African country known for the Sahara Desert and the ancient trading city of Agadez.',
    'Nigeria': 'The most populous country in Africa, known for its Nollywood film industry, Afrobeat music, and vibrant city of Lagos.',
    'North Macedonia': 'A Balkan country known for its rich history, Ohrid Lake, and being the birthplace of Alexander the Great.',
    'Norway': 'A Scandinavian country known for its stunning fjords, Northern Lights, and being one of the happiest countries in the world.',
    'Oman': 'A Middle Eastern country known for its historic forts, the bustling souks of Muscat, and the frankincense trade that dates back thousands of years.',
    'Pakistan': 'A South Asian country known for its majestic mountain ranges, including K2, the second-highest peak in the world, and its rich history with ancient sites like Mohenjo-Daro.',
    'Palau': 'A Pacific island nation famous for its stunning marine environment, including Jellyfish Lake, where you can swim among thousands of harmless jellyfish.',
    'Palestine': 'A region in the Middle East known for its historical and religious significance, particularly the cities of Bethlehem and Jerusalem, which are sacred to Jews, Christians, and Muslims.',
    'Panama': 'A Central American country known for the Panama Canal, a vital shortcut for global maritime trade that connects the Atlantic and Pacific Oceans.',
    'Papua New Guinea': 'An island nation in Oceania known for its incredible cultural diversity, with over 800 languages spoken, and its dense rainforests and unique wildlife.',
    'Paraguay': 'A landlocked South American country known for its large rivers, the Itaipu Dam (one of the world\'s largest hydroelectric plants), and its bilingual culture (Spanish and Guarani).',
    'Peru': 'A South American country famous for the ancient Inca city of Machu Picchu, high in the Andes Mountains, and for the vibrant culture of the indigenous Quechua people.',
    'Philippines': 'A Southeast Asian archipelago consisting of over 7,000 islands, known for its beautiful beaches, rice terraces, and vibrant festivals like Sinulog and Ati-Atihan.',
    'Poland': 'A European country known for its medieval castles, the historic city of Kraków, and the Auschwitz-Birkenau concentration camp memorial.',
    'Portugal': 'A European country known for its maritime explorers, stunning coastal cliffs, and the production of port wine in the Douro Valley.',
    'Qatar': 'A small, wealthy country in the Middle East known for its futuristic skyscrapers, hosting the 2022 FIFA World Cup, and its vast natural gas reserves.',
    'Romania': 'A European country known for the legend of Dracula, medieval castles like Bran Castle, and the scenic Carpathian Mountains.',
    'Russia': 'The largest country in the world, spanning Europe and Asia, known for its vast Siberian wilderness, the Red Square in Moscow, and its rich cultural history.',
    'Rwanda': 'An East African country known as the "Land of a Thousand Hills" for its mountainous terrain, and for its mountain gorillas, which can be seen in Volcanoes National Park.',
    'Saint Kitts and Nevis': 'The smallest country in the Western Hemisphere, consisting of two main islands, known for its sugar plantations and scenic railway tours.',
    'Saint Lucia': 'A Caribbean island nation known for its iconic twin peaks, the Pitons, and the world\'s only drive-in volcano.',
    'Saint Vincent and the Grenadines': 'A Caribbean nation consisting of one main island and several smaller ones, known for its pristine beaches and filming locations for "Pirates of the Caribbean."',
    'Samoa': 'A Pacific island country known for its traditional culture called "fa\'a Samoa," spectacular waterfalls, and the To Sua Ocean Trench, a famous natural swimming hole.',
    'San Marino': 'A tiny landlocked country surrounded by Italy, known for being one of the world\'s oldest republics and its medieval fortresses perched on Mount Titano.',
    'Sao Tome and Principe': 'A small island nation in the Gulf of Guinea, known for its cocoa plantations, unique biodiversity, and beautiful volcanic landscapes.',
    'Saudi Arabia': 'A Middle Eastern country known for being the birthplace of Islam, housing the holy cities of Mecca and Medina, and its vast desert landscapes.',
    'Senegal': 'A West African country known for its vibrant music scene, especially mbalax, the Pink Lake (Lake Retba), and the historic slave trade island of Gorée.',
    'Serbia': 'A Balkan country known for its capital, Belgrade, lively festivals, and historical monasteries scattered throughout the country.',
    'Seychelles': 'An archipelago in the Indian Ocean known for its stunning beaches, unique granite rock formations, and rich marine life, making it a top honeymoon destination.',
    'Sierra Leone': 'A West African country known for its beautiful beaches, diamond mines, and being one of the countries with the highest biodiversity in Africa.',
    'Singapore': 'A city-state in Southeast Asia known for its rapid development, modern skyline with Marina Bay Sands, strict laws, and multicultural society.',
    'Slovakia': 'A Central European country known for its dramatic mountain ranges, medieval castles, and the charming old town of Bratislava, its capital.',
    'Slovenia': 'A small European country known for its picturesque Lake Bled, stunning caves like Postojna, and being one of the greenest countries in the world.',
    'Solomon Islands': 'A Pacific nation known for its World War II history, especially the Battle of Guadalcanal, and beautiful coral reefs.',
    'Somalia': 'An East African country with the longest coastline on mainland Africa, known for its ancient maritime trade history and cultural traditions like poetry.',
    'South Africa': 'A country on the southern tip of Africa known for its diverse landscapes, from safaris in Kruger National Park to the vibrant city of Cape Town and its symbol of the anti-apartheid struggle, Nelson Mandela.',
    'South Sudan': 'The world\'s youngest country, gaining independence from Sudan in 2011, known for its rich cultural diversity and the vast Sudd swamp.',
    'Spain': 'A European country known for its flamenco dance, tapas, vibrant festivals like La Tomatina and Running of the Bulls, and landmarks like the Alhambra and Sagrada Família.',
    'Sri Lanka': 'An island nation in the Indian Ocean known as the "Pearl of the Indian Ocean," famous for its ancient temples, tea plantations, and diverse wildlife.',
    'Sudan': 'A North African country known for its ancient pyramids in Meroë, along the Nile River, and its long history that intersects with that of ancient Egypt.',
    'Suriname': 'The smallest country in South America, known for its tropical rainforests, multicultural society, and Dutch colonial architecture.',
    'Sweden': 'A Scandinavian country known for its high standard of living, beautiful landscapes with thousands of lakes, and being the birthplace of brands like IKEA and Volvo.',
    'Switzerland': 'A landlocked European country famous for its Alps, precision watches, chocolate, and neutrality in international conflicts.',
    'Syria': 'A Middle Eastern country with a rich history dating back to ancient civilizations, known for its historic cities like Damascus and Palmyra.',
    'Taiwan': 'An island off the coast of China, known for its vibrant night markets, bubble tea, and being one of the world\'s top producers of semiconductors.',
    'Tajikistan': 'A Central Asian country known for its stunning Pamir Mountains, often called the "Roof of the World," and its Silk Road heritage.',
    'Tanzania': 'An East African country famous for Mount Kilimanjaro, Africa\'s highest peak, and the Serengeti National Park, known for the Great Migration of wildebeest.',
    'Thailand': 'A Southeast Asian country known for its beautiful beaches, vibrant street food culture, and temples like Wat Phra Kaew in Bangkok.',
    'Togo': 'A small West African country known for its palm-lined beaches, hilltop villages, and the UNESCO World Heritage site Koutammakou, the Land of the Batammariba.',
    'Tonga': 'A Polynesian kingdom of more than 170 South Pacific islands, known for its rich cultural traditions and being the only monarchy in the Pacific.',
    'Trinidad and Tobago': 'A Caribbean nation known for its annual Carnival, steelpan music, and diverse wildlife, including the world\'s largest brain coral.',
    'Tunisia': 'A North African country known for its ancient ruins like Carthage, the desert landscapes of the Sahara, and its role in the "Arab Spring" revolutions.',
    'Turkey': 'A country that straddles Europe and Asia, known for its rich history in cities like Istanbul (formerly Constantinople), the Hagia Sophia, and unique landscapes like Cappadocia.',
    'Turkmenistan': 'A Central Asian country known for its vast deserts, the ancient Silk Road city of Merv, and the Darvaza Gas Crater, also known as the "Door to Hell."',
    'Tuvalu': 'One of the smallest and least populated countries in the world, located in the Pacific Ocean and known for its vulnerability to rising sea levels due to climate change.',
    'Uganda': 'An East African country known as the "Pearl of Africa," famous for its mountain gorillas in Bwindi Impenetrable National Park and the source of the Nile River.',
    'Ukraine': 'A large Eastern European country known for its vast wheat fields (earning it the nickname "breadbasket of Europe"), rich cultural heritage, and historic cities like Kyiv.',
    'United Arab Emirates': 'A Middle Eastern country known for its ultra-modern skyscrapers, luxury shopping, and iconic landmarks like the Burj Khalifa in Dubai, the world\'s tallest building.',
    'United Kingdom (UK)': 'A European country made up of England, Scotland, Wales, and Northern Ireland, known for its royal family, historical landmarks like Buckingham Palace and Stonehenge, and being the birthplace of Shakespeare.',
    'United States of America': 'A large and diverse country in North America known for its global cultural influence, iconic landmarks like the Statue of Liberty, the Grand Canyon, and Hollywood.',
    'Uruguay': 'A South American country known for its beach-lined coast, the laid-back capital Montevideo, and being one of the first countries in the world to legalize recreational cannabis.',
    'Uzbekistan': 'A Central Asian country known for its Silk Road cities like Samarkand, Bukhara, and Khiva, famous for their stunning Islamic architecture and ancient mosques.',
    'Vanuatu': 'A Pacific island nation known for its active volcanoes, traditional Melanesian culture, and unique land diving ritual called "naghol," which is a precursor to modern bungee jumping.',
    'Vatican City': 'The smallest country in the world, located within Rome, Italy, and known as the spiritual and administrative center of the Roman Catholic Church, where the Pope resides.',
    'Venezuela': 'A South American country known for Angel Falls, the world\'s highest uninterrupted waterfall, and its vast oil reserves.',
    'Vietnam': 'A Southeast Asian country famous for its vibrant cities like Hanoi and Ho Chi Minh City, delicious street food like pho and banh mi, and scenic landscapes such as Ha Long Bay.',
    'Yemen': 'A Middle Eastern country known for its ancient city of Sana\'a, a UNESCO World Heritage Site, and the unique terraced fields and mud-brick skyscrapers of Shibam.',
    'Zambia': 'A landlocked country in Southern Africa known for Victoria Falls, one of the largest and most famous waterfalls in the world, shared with Zimbabwe.',
    'Zimbabwe': 'A Southern African country known for the Great Z Ruins, an ancient city that was the capital of the Kingdom of Z, and also for its side of Victoria Falls.'
}

# Extract all country names
country_names = list(countryFacts.keys())

# Print each country name on a new line
for country in country_names:
    print(country)